# Generated by Django 4.2 on 2026-08-03 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAthleteRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('primary', 'Entrenador/a principal'), ('assistant', 'Entrenador/a assistent'), ('physical', 'Preparació física'), ('choreographer', 'Coreografia'), ('other', 'Altres')], default='primary', max_length=20)),
                ('can_view_profile', models.BooleanField(default=True)),
                ('can_view_training', models.BooleanField(default=True)),
                ('can_edit_training', models.BooleanField(default=False)),
                ('can_view_health_data', models.BooleanField(default=False, help_text="Permís sensible que s'ha de concedir explícitament.")),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('athlete_id', 'coach_id', 'function'),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Responsable'), ('admin', 'Administració'), ('coach', 'Entrenador/a'), ('athlete', 'Gimnasta'), ('staff', 'Personal'), ('member', 'Membre')], default='member', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('organization_id', 'person_id', 'role'),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('club', 'Club'), ('federation', 'Federació'), ('other', 'Altres')], default='club', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['kind', 'is_active'], name='core_org_kind_active_idx'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.person'),
        ),
        migrations.AddField(
            model_name='coachathleterelation',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_relations', to='core.person'),
        ),
        migrations.AddField(
            model_name='coachathleterelation',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_relations', to='core.person'),
        ),
        migrations.AddField(
            model_name='coachathleterelation',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Organització en què s'aplica la relació; buit si és global.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_athlete_relations', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='core_person_name_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active'], name='core_person_active_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='core_member_org_role_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['person', 'is_active'], name='core_member_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('person', 'organization', 'role'), name='core_membership_uniq_role'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='core_membership_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='coachathleterelation',
            index=models.Index(fields=['coach', 'is_active'], name='core_rel_coach_active_idx'),
        ),
        migrations.AddIndex(
            model_name='coachathleterelation',
            index=models.Index(fields=['athlete', 'is_active'], name='core_rel_athlete_active_idx'),
        ),
        migrations.AddIndex(
            model_name='coachathleterelation',
            index=models.Index(fields=['organization', 'is_active'], name='core_rel_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.CheckConstraint(check=models.Q(('coach', models.F('athlete')), _negated=True), name='core_relation_distinct_people'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='core_relation_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.CheckConstraint(check=models.Q(('can_edit_training', False), ('can_view_training', True), _connector='OR'), name='core_relation_edit_implies_view'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.CheckConstraint(check=models.Q(('can_view_health_data', False), ('can_view_profile', True), _connector='OR'), name='core_relation_health_profile'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('coach', 'athlete', 'organization', 'function'), name='core_relation_uniq_context'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('coach', 'athlete', 'function'), name='core_relation_uniq_global'),
        ),
    ]
