# Generated by Django 4.2 on 2026-08-04 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_missing_people(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    Person = apps.get_model("core", "Person")
    linked_user_ids = set(
        Person.objects.exclude(user_id=None).values_list("user_id", flat=True)
    )
    people = []
    for user in User.objects.exclude(pk__in=linked_user_ids).iterator():
        people.append(
            Person(
                user_id=user.pk,
                first_name=(user.first_name or user.username).strip(),
                last_name=(user.last_name or "").strip(),
                email=(user.email or "").strip(),
                is_provisional=True,
            )
        )
    Person.objects.bulk_create(people, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_organization_membership_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonClaimInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendent'), ('claimed', 'Reclamada'), ('cancelled', 'Cancel·lada'), ('expired', 'Caducada')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_person_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PersonMergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate_person_id', models.PositiveBigIntegerField(unique=True)),
                ('duplicate_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='is_provisional',
            field=models.BooleanField(default=False, help_text='Identitat creada automàticament amb el compte i encara no confirmada.'),
        ),
        migrations.RunPython(create_missing_people, migrations.RunPython.noop),
        migrations.AddField(
            model_name='personmergerecord',
            name='canonical_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absorbed_identity_records', to='core.person'),
        ),
        migrations.AddField(
            model_name='personmergerecord',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_merge_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personclaiminvitation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_person_claim_invitations', to='core.person'),
        ),
        migrations.AddField(
            model_name='personclaiminvitation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_invitations', to='core.person'),
        ),
        migrations.AddIndex(
            model_name='personclaiminvitation',
            index=models.Index(fields=['person', 'status'], name='core_claim_person_idx'),
        ),
        migrations.AddIndex(
            model_name='personclaiminvitation',
            index=models.Index(fields=['email', 'status'], name='core_claim_email_idx'),
        ),
    ]
