# Generated by Django 4.0.4 on 2026-08-18 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_release_organization_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Identificador semàntic estable, independent de l'idioma i del nom visible.", max_length=100, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('definition', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('segment', 'Segment corporal funcional'), ('joint', 'Articulació o complex articular'), ('joint_action', 'Acció articular'), ('plane', 'Pla anatòmic'), ('axis', 'Eix anatòmic'), ('body_configuration', 'Configuració corporal'), ('kinematic_event', 'Esdeveniment cinemàtic')], max_length=40)),
                ('laterality', models.CharField(choices=[('not_applicable', 'No aplicable'), ('unpaired', 'Estructura no parella'), ('midline', 'Estructura medial'), ('paired', 'Estructura parella')], default='not_applicable', help_text="Classifica l'estructura; els costats concrets es modelaran en l'esquelet o l'ús.", max_length=20)),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Fonts, correspondències externes i notes de procedència estructurades.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_motion_concepts', to='core.person')),
                ('last_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_motion_concepts', to='core.person')),
            ],
            options={
                'ordering': ('kind', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MotionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('part_of', 'Forma part de'), ('proximal_segment', 'Té com a segment proximal'), ('distal_segment', 'Té com a segment distal'), ('action_at_joint', "Es produeix a l'articulació"), ('primary_plane', 'Es produeix principalment al pla'), ('primary_axis', "Es produeix principalment al voltant de l'eix"), ('opposite_of', 'És oposada a')], max_length=40)),
                ('rationale', models.TextField(blank=True, default='')),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_motion_relations', to='core.person')),
                ('last_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_motion_relations', to='core.person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_motion_relations', to='iatrain_motion.motionconcept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_motion_relations', to='iatrain_motion.motionconcept')),
            ],
            options={
                'ordering': ('source_id', 'relation_type', 'target_id'),
            },
        ),
        migrations.AddIndex(
            model_name='motionrelation',
            index=models.Index(fields=['source', 'relation_type', 'editorial_status'], name='motion_rel_source_idx'),
        ),
        migrations.AddIndex(
            model_name='motionrelation',
            index=models.Index(fields=['target', 'relation_type', 'editorial_status'], name='motion_rel_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='motionrelation',
            constraint=models.CheckConstraint(check=models.Q(('source', django.db.models.expressions.F('target')), _negated=True), name='motion_relation_distinct_nodes'),
        ),
        migrations.AddConstraint(
            model_name='motionrelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='motion_relation_uniq_edge'),
        ),
        migrations.AddConstraint(
            model_name='motionrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('relation_type__in', ('proximal_segment', 'distal_segment', 'action_at_joint', 'primary_plane', 'primary_axis'))), fields=('source', 'relation_type'), name='motion_relation_uniq_functional'),
        ),
        migrations.AddIndex(
            model_name='motionconcept',
            index=models.Index(fields=['kind', 'editorial_status'], name='motion_concept_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='motionconcept',
            index=models.Index(fields=['authored_by', 'created_at'], name='motion_concept_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='motionconcept',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.expressions.F('kind'), name='motion_concept_uniq_name_kind'),
        ),
    ]
