# Generated by Django 4.0.4 on 2026-08-18 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_release_organization_models'),
        ('iatrain_motion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120)),
                ('side', models.CharField(choices=[('none', 'Sense lateralitat'), ('midline', 'Medial'), ('left', 'Esquerra'), ('right', 'Dreta')], default='none', max_length=20)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_authored', to='core.person')),
            ],
            options={
                'ordering': ('schema_id', 'side', 'code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CanonicalLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=220)),
                ('definition', models.TextField(blank=True, default='')),
                ('landmark_type', models.CharField(choices=[('anatomical', 'Punt anatòmic'), ('joint_center', 'Centre articular'), ('virtual', 'Punt virtual derivat'), ('terminal', 'Punt terminal de segment')], max_length=30)),
                ('measurement_source', models.CharField(choices=[('observed', "Observable o mapable des d'un tracker"), ('derived', "Derivat d'altres punts"), ('estimated', 'Centre o punt estimat')], max_length=20)),
                ('side', models.CharField(choices=[('none', 'Sense lateralitat'), ('midline', 'Medial'), ('left', 'Esquerra'), ('right', 'Dreta')], default='none', max_length=20)),
                ('derivation', models.JSONField(blank=True, default=dict)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_authored', to='core.person')),
            ],
            options={
                'ordering': ('schema_id', 'side', 'code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SkeletonSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('spatial_dimensions', models.PositiveSmallIntegerField(choices=[(2, '2D'), (3, '3D')], default=3)),
                ('length_unit', models.CharField(default='metre', max_length=20)),
                ('angle_unit', models.CharField(default='radian', max_length=20)),
                ('coordinate_convention', models.JSONField(default=dict)),
                ('neutral_pose', models.JSONField(default=dict)),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_skeleton_schemas', to='core.person')),
                ('last_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_skeleton_schemas', to='core.person')),
            ],
            options={
                'ordering': ('code', 'version', 'id'),
            },
        ),
        migrations.CreateModel(
            name='JointAngleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=140)),
                ('component', models.CharField(choices=[('flexion_extension', 'Flexió-extensió'), ('abduction_adduction', 'Abducció-adducció'), ('axial_rotation', 'Rotació axial')], max_length=40)),
                ('sequence_index', models.PositiveSmallIntegerField(default=1)),
                ('calculation_method', models.CharField(choices=[('projected_planar', 'Angle planar projectat'), ('joint_coordinate_system', 'Sistema de coordenades articular')], max_length=40)),
                ('sign_convention', models.TextField()),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_authored', to='core.person')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='axial_joint_angle_definitions', to='iatrain_motion.motionconcept')),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='angle_definitions', to='iatrain_motion.canonicaljoint')),
                ('negative_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negative_joint_angle_definitions', to='iatrain_motion.motionconcept')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planar_joint_angle_definitions', to='iatrain_motion.motionconcept')),
                ('positive_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positive_joint_angle_definitions', to='iatrain_motion.motionconcept')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angle_definitions', to='iatrain_motion.skeletonschema')),
            ],
            options={
                'ordering': ('schema_id', 'joint_id', 'sequence_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CanonicalSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120)),
                ('side', models.CharField(choices=[('none', 'Sense lateralitat'), ('midline', 'Medial'), ('left', 'Esquerra'), ('right', 'Dreta')], default='none', max_length=20)),
                ('orientation_capability', models.CharField(choices=[('long_axis_only', 'Només eix longitudinal'), ('full_3d', 'Orientació tridimensional')], default='long_axis_only', max_length=30)),
                ('primary_axis', models.CharField(choices=[('longitudinal', 'Longitudinal'), ('mediolateral', 'Mediolateral')], default='longitudinal', max_length=20)),
                ('frame_notes', models.TextField(blank=True, default='')),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_authored', to='core.person')),
                ('axis_end_landmark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segment_axes_ending_here', to='iatrain_motion.canonicallandmark')),
                ('axis_start_landmark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segment_axes_starting_here', to='iatrain_motion.canonicallandmark')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_segment_instances', to='iatrain_motion.motionconcept')),
                ('plane_landmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segments_defining_plane_here', to='iatrain_motion.canonicallandmark')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='iatrain_motion.skeletonschema')),
            ],
            options={
                'ordering': ('schema_id', 'side', 'code', 'id'),
            },
        ),
        migrations.AddField(
            model_name='canonicallandmark',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='iatrain_motion.skeletonschema'),
        ),
        migrations.AddField(
            model_name='canonicaljoint',
            name='center_landmark',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='joint_definition', to='iatrain_motion.canonicallandmark'),
        ),
        migrations.AddField(
            model_name='canonicaljoint',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_joint_instances', to='iatrain_motion.motionconcept'),
        ),
        migrations.AddField(
            model_name='canonicaljoint',
            name='distal_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proximal_joints', to='iatrain_motion.canonicalsegment'),
        ),
        migrations.AddField(
            model_name='canonicaljoint',
            name='proximal_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distal_joints', to='iatrain_motion.canonicalsegment'),
        ),
        migrations.AddField(
            model_name='canonicaljoint',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joints', to='iatrain_motion.skeletonschema'),
        ),
        migrations.AddIndex(
            model_name='skeletonschema',
            index=models.Index(fields=['editorial_status', 'code'], name='skeleton_schema_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='skeletonschema',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), django.db.models.expressions.F('version'), name='skeleton_schema_uniq_version'),
        ),
        migrations.AddConstraint(
            model_name='jointangledefinition',
            constraint=models.UniqueConstraint(fields=('schema', 'code'), name='skeleton_angle_uniq_code'),
        ),
        migrations.AddConstraint(
            model_name='jointangledefinition',
            constraint=models.UniqueConstraint(fields=('joint', 'component'), name='skeleton_angle_uniq_component'),
        ),
        migrations.AddConstraint(
            model_name='jointangledefinition',
            constraint=models.CheckConstraint(check=models.Q(('positive_action', django.db.models.expressions.F('negative_action')), _negated=True), name='skeleton_angle_distinct_actions'),
        ),
        migrations.AddConstraint(
            model_name='jointangledefinition',
            constraint=models.CheckConstraint(check=models.Q(('sequence_index__gte', 1), ('sequence_index__lte', 3)), name='skeleton_angle_sequence_range'),
        ),
        migrations.AddConstraint(
            model_name='canonicalsegment',
            constraint=models.UniqueConstraint(fields=('schema', 'code'), name='skeleton_segment_uniq_code'),
        ),
        migrations.AddConstraint(
            model_name='canonicalsegment',
            constraint=models.UniqueConstraint(fields=('schema', 'concept', 'side'), name='skeleton_segment_uniq_semantic'),
        ),
        migrations.AddConstraint(
            model_name='canonicalsegment',
            constraint=models.CheckConstraint(check=models.Q(('axis_start_landmark', django.db.models.expressions.F('axis_end_landmark')), _negated=True), name='skeleton_segment_distinct_ends'),
        ),
        migrations.AddIndex(
            model_name='canonicallandmark',
            index=models.Index(fields=['schema', 'side'], name='skeleton_landmark_side_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicallandmark',
            constraint=models.UniqueConstraint(fields=('schema', 'code'), name='skeleton_landmark_uniq_code'),
        ),
        migrations.AddConstraint(
            model_name='canonicaljoint',
            constraint=models.UniqueConstraint(fields=('schema', 'code'), name='skeleton_joint_uniq_code'),
        ),
        migrations.AddConstraint(
            model_name='canonicaljoint',
            constraint=models.UniqueConstraint(fields=('schema', 'concept', 'side'), name='skeleton_joint_uniq_semantic'),
        ),
        migrations.AddConstraint(
            model_name='canonicaljoint',
            constraint=models.CheckConstraint(check=models.Q(('proximal_segment', django.db.models.expressions.F('distal_segment')), _negated=True), name='skeleton_joint_distinct_segments'),
        ),
    ]
