# Generated by Django 4.0.4 on 2026-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iatrain_motion', '0002_canonicaljoint_canonicallandmark_skeletonschema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skeletonschema',
            name='coordinate_convention',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='skeletonschema',
            name='neutral_pose',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
