# Generated by Django 4.2 on 2026-08-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iatrain_motion', '0003_alter_skeletonschema_coordinate_convention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionconcept',
            name='kind',
            field=models.CharField(choices=[('segment', 'Segment corporal funcional'), ('joint', 'Articulació o complex articular'), ('joint_action', 'Acció articular'), ('plane', 'Pla anatòmic'), ('axis', 'Eix anatòmic'), ('body_configuration', 'Configuració corporal'), ('kinematic_event', 'Esdeveniment cinemàtic'), ('muscle', 'Múscul esquelètic funcional'), ('muscle_group', 'Grup muscular funcional')], max_length=40),
        ),
        migrations.AlterField(
            model_name='motionrelation',
            name='relation_type',
            field=models.CharField(choices=[('part_of', 'Forma part de'), ('proximal_segment', 'Té com a segment proximal'), ('distal_segment', 'Té com a segment distal'), ('action_at_joint', "Es produeix a l'articulació"), ('primary_plane', 'Es produeix principalment al pla'), ('primary_axis', "Es produeix principalment al voltant de l'eix"), ('opposite_of', 'És oposada a'), ('member_of_muscle_group', 'Forma part del grup muscular'), ('spans_joint', "Travessa funcionalment l'articulació")], max_length=40),
        ),
    ]
