# Generated by Django 4.2 on 2026-08-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iatrain_motion', '0004_alter_motionconcept_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointangledefinition',
            name='component',
            field=models.CharField(choices=[('flexion_extension', 'Flexió-extensió'), ('abduction_adduction', 'Abducció-adducció'), ('axial_rotation', 'Rotació axial'), ('horizontal_abduction_adduction', 'Abducció-adducció horitzontal'), ('radial_ulnar_deviation', 'Desviació radial-cubital'), ('inversion_eversion', 'Inversió-eversió')], max_length=40),
        ),
    ]
