CATALOG_VERSION = "private_exercise_catalog_v2_2026_08_20"

SOURCES = {
    "acsm_resistance_2026": {
        "url": "https://pubmed.ncbi.nlm.nih.gov/41843416/",
        "source_type": "scientific_position_stand",
        "accessed_on": "2026-08-20",
        "rationale": "Marc actualitzat per distingir força, potència, resistència i selecció d'exercicis sense convertir la dosificació en identitat.",
    },
    "acsm_progression_2002": {
        "url": "https://pubmed.ncbi.nlm.nih.gov/11828249/",
        "source_type": "scientific_position_stand",
        "accessed_on": "2026-08-20",
        "rationale": "Dóna suport a incloure exercicis monoarticulars i multiarticulars i accions concèntriques i excèntriques.",
    },
    "squat_review_2024": {
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10987311/",
        "source_type": "peer_reviewed_biomechanical_review",
        "accessed_on": "2026-08-20",
        "rationale": "Descriu com suport, amplada, tronc, tíbia i profunditat diferencien variants reals de l'esquat.",
    },
    "deadlift_emg_review": {
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7046193/",
        "source_type": "systematic_review",
        "accessed_on": "2026-08-20",
        "rationale": "Sosté l'existència de variants de pes mort i la prudència en atribuir activació muscular específica.",
    },
    "unilateral_meta_analysis": {
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9331349/",
        "source_type": "systematic_review_meta_analysis",
        "accessed_on": "2026-08-20",
        "rationale": "Justifica separar exercicis unilaterals i bilaterals per especificitat mecànica i de rendiment.",
    },
    "bench_press_review": {
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5295722/",
        "source_type": "systematic_review",
        "accessed_on": "2026-08-20",
        "rationale": "Documenta variants de pressió horitzontal i la variabilitat d'activació segons presa, càrrega i rang.",
    },
    "chest_kinematics": {
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8877248/",
        "source_type": "peer_reviewed_biomechanics_study",
        "accessed_on": "2026-08-20",
        "rationale": "Compara cinemàtica de press de banca inclinat, pla i politges i informa la classificació de les variants.",
    },
    "overhead_press_review": {
        "url": "https://pubmed.ncbi.nlm.nih.gov/30924081/",
        "source_type": "scientific_review",
        "accessed_on": "2026-08-20",
        "rationale": "Diferencia press estricte, push press i derivats per demanda tècnica i producció de força.",
    },
    "weightlifting_derivatives": {
        "url": "https://pubmed.ncbi.nlm.nih.gov/25689955/",
        "source_type": "scientific_review",
        "accessed_on": "2026-08-20",
        "rationale": "Sosté derivats de tracció sense recepció i registra que exigeixen tècnica i supervisió.",
    },
    "weightlifting_meta_analysis": {
        "url": "https://pubmed.ncbi.nlm.nih.gov/35025093/",
        "source_type": "systematic_review_meta_analysis",
        "accessed_on": "2026-08-20",
        "rationale": "Dóna suport a incloure salts, pliometria i derivats d'halterofília com a exercicis de potència diferenciats.",
    },
    "core_prescription_review": {
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3806181/",
        "source_type": "peer_reviewed_clinical_review",
        "accessed_on": "2026-08-20",
        "rationale": "Defineix control del tronc i diferencia funcions locals i globals sense afirmar superioritat clínica.",
    },
    "core_stability_critical_review": {
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4647147/",
        "source_type": "critical_scientific_review",
        "accessed_on": "2026-08-20",
        "rationale": "Justifica llenguatge prudent sobre estabilitat i evita prometre prevenció o transferència no demostrades.",
    },
    "mobility_meta_analysis": {
        "url": "https://pubmed.ncbi.nlm.nih.gov/36622555/",
        "source_type": "systematic_review_meta_analysis",
        "accessed_on": "2026-08-20",
        "rationale": "Sosté incloure exercicis de força en rang controlat amb objectiu secundari de mobilitat.",
    },
    "stretching_consensus": {
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12305623/",
        "source_type": "expert_consensus",
        "accessed_on": "2026-08-20",
        "rationale": "Informa la inclusió prudent de mobilitat dinàmica i l'exclusió de promeses universals d'escalfament o prevenció.",
    },
    "who_activity_guidelines": {
        "url": "https://iris.who.int/bitstream/handle/10665/336656/9789240015128-eng.pdf",
        "source_type": "official_guideline",
        "accessed_on": "2026-08-20",
        "rationale": "Marc institucional per cobrir els grans grups musculars sense prescriure dosis dins de l'exercici.",
    },
    "ace_applied_science": {
        "url": "https://www.acefitness.org/academy/AcademyElitePDFs/ESS-AES_Download_Final.pdf",
        "source_type": "professional_educational_resource",
        "accessed_on": "2026-08-20",
        "rationale": "Recurs educatiu per contrastar accions articulars i exemples de patrons; les descripcions s'han redactat de nou.",
    },
    "ace_cable_exercises": {
        "url": "https://www.acefitness.org/cp/pdfs/CertifiedNews/AugSept09Cert.pdf",
        "source_type": "professional_educational_resource",
        "accessed_on": "2026-08-20",
        "rationale": "Contrasta variants habituals de politja, rem i jaló sense copiar-ne les instruccions.",
    },
    "ace_shoulder_study": {
        "url": "https://www.acefitness.org/certifiednews/images/article/pdfs/ACEShoulderStudy.pdf",
        "source_type": "professional_research_summary",
        "accessed_on": "2026-08-20",
        "rationale": "Ajuda a cobrir variants de l'espatlla amb una atribució muscular conservadora.",
    },
    "openstax_lower_limb": {
        "url": "https://openstax.org/books/anatomy-and-physiology-2e/pages/11-6-appendicular-muscles-of-the-pelvic-girdle-and-lower-limbs",
        "source_type": "open_textbook",
        "accessed_on": "2026-08-20",
        "rationale": "Font anatòmica ja utilitzada per la base professional d'IA Train per a l'extremitat inferior.",
    },
    "openstax_upper_limb": {
        "url": "https://openstax.org/books/anatomy-and-physiology-2e/pages/11-5-muscles-of-the-pectoral-girdle-and-upper-limbs",
        "source_type": "open_textbook",
        "accessed_on": "2026-08-20",
        "rationale": "Font anatòmica ja utilitzada per la base professional d'IA Train per a l'extremitat superior.",
    },
    "openstax_axial": {
        "url": "https://openstax.org/books/anatomy-and-physiology-2e/pages/11-4-axial-muscles-of-the-abdominal-wall-and-thorax",
        "source_type": "open_textbook",
        "accessed_on": "2026-08-20",
        "rationale": "Font anatòmica ja utilitzada per la base professional d'IA Train per al tronc.",
    },
}

EQUIPMENT = (
    ("barbell", "Barra", "free_weight"),
    ("dumbbell", "Mancuerna", "free_weight"),
    ("kettlebell", "Kettlebell", "free_weight"),
    ("weight_plate", "Disc de pes", "free_weight"),
    ("trap_bar", "Barra hexagonal", "free_weight"),
    ("bench", "Banc", "support"),
    ("box", "Caixa pliomètrica", "support"),
    ("step_platform", "Esglaó d'entrenament", "support"),
    ("wall", "Paret", "support"),
    ("mat", "Matalàs fi", "support"),
    ("foam_roller", "Corró d'escuma", "support"),
    ("elastic_band", "Banda elàstica", "elastic"),
    ("cable_machine", "Politja", "machine"),
    ("smith_machine", "Màquina Smith", "machine"),
    ("leg_press_machine", "Màquina de premsa de cames", "machine"),
    ("hack_squat_machine", "Màquina de hack squat", "machine"),
    ("leg_extension_machine", "Màquina d'extensió de genoll", "machine"),
    ("leg_curl_machine", "Màquina de flexió de genoll", "machine"),
    ("resistance_machine", "Màquina de resistència guiada", "machine"),
    ("roman_chair", "Banc romà", "support"),
    ("suspension_trainer", "Sistema de suspensió", "suspension"),
    ("pull_up_bar", "Barra de dominades", "support"),
    ("landmine", "Ancoratge landmine", "support"),
    ("stability_ball", "Pilota d'estabilitat", "other"),
    ("medicine_ball", "Pilota medicinal", "other"),
    ("slider", "Disc lliscant", "other"),
)

PROFESSIONAL_GAPS = (
    {"code": "forearm_pronation_supination", "status": "pending", "layer": "iatrain_motion_and_biomechanics", "blocked_examples": ["pronation_curl", "supination_curl"], "rationale": "No hi ha accions canòniques de pronació/supinació ni funcions associades; no s'han creat substituts aproximats."},
    {"code": "toe_actions_and_intrinsic_foot", "status": "pending", "layer": "iatrain_motion_and_biomechanics", "blocked_examples": ["short_foot", "toe_yoga"], "rationale": "La base no representa accions dels dits ni musculatura intrínseca del peu."},
    {"code": "scapular_stabilizers_not_all_typed", "status": "pending", "layer": "iatrain_biomechanics", "blocked_examples": ["scapular_wall_slide_with_full_role_set"], "rationale": "Hi ha funcions de serrat i trapezi mitjà/inferior, però no per tots els músculs escapulars disponibles."},
    {"code": "cervical_stabilization_functions", "status": "pending", "layer": "iatrain_biomechanics", "blocked_examples": ["neck_isometric_series"], "rationale": "Hi ha accions cervicals però no funcions estabilitzadores cervicals tipades."},
    {"code": "elbow_forearm_grip_model", "status": "pending", "layer": "iatrain_motion_and_biomechanics", "blocked_examples": ["farmers_carry_grip_roles", "wrist_roller"], "rationale": "La presa i els flexors dels dits no tenen encara una representació professional completa."},
    {"code": "movement_actions_for_loaded_carries", "status": "pending", "layer": "iatrain_motion", "blocked_examples": ["farmers_carry", "suitcase_carry"], "rationale": "La locomoció existeix com patró privat però no hi ha accions professionals suficients per fases de marxa i suport."},
)

