from .athletes import athlete_create, athlete_detail, athlete_list
from .dashboard import home
from .engine import (
    block_generation_apply,
    block_generation_create,
    block_generation_decide,
    block_generation_discard,
    block_generation_refine,
    block_generation_status,
    context_options,
    training_start,
)
from .groups import group_create, group_detail, group_list, group_member_remove
from .gyms import (
    gym_create,
    gym_detail,
    gym_edit,
    gym_equipment_create,
    gym_equipment_edit,
    gym_list,
)
from .organizations import organization_detail, organization_list
from .profiles import select_perspective, update_profile
from .reviews import (
    condition_resolve,
    condition_review,
    insight_review,
    profile_review,
)
from .sessions import (
    session_block_delete,
    session_block_edit,
    session_detail,
    session_goal_delete,
    session_item_create,
    session_item_adjustment_edit,
    session_item_delete,
    session_item_edit,
    session_list,
    session_participant_delete,
    session_revision_transition,
)
from .knowledge_graph import (
    knowledge_concept_status,
    knowledge_graph,
    knowledge_graph_data,
    knowledge_relation_status,
    motion_concept_status,
    motion_relation_status,
)
from .library import library

__all__ = (
    "athlete_create",
    "athlete_detail",
    "athlete_list",
    "block_generation_apply",
    "block_generation_create",
    "block_generation_decide",
    "block_generation_discard",
    "block_generation_refine",
    "block_generation_status",
    "context_options",
    "condition_resolve",
    "condition_review",
    "group_create",
    "group_detail",
    "group_list",
    "group_member_remove",
    "gym_create",
    "gym_detail",
    "gym_edit",
    "gym_equipment_create",
    "gym_equipment_edit",
    "gym_list",
    "home",
    "knowledge_concept_status",
    "knowledge_graph",
    "knowledge_graph_data",
    "knowledge_relation_status",
    "library",
    "insight_review",
    "motion_concept_status",
    "motion_relation_status",
    "organization_detail",
    "organization_list",
    "profile_review",
    "select_perspective",
    "session_block_delete",
    "session_block_edit",
    "session_detail",
    "session_goal_delete",
    "session_item_create",
    "session_item_adjustment_edit",
    "session_item_delete",
    "session_item_edit",
    "session_list",
    "session_participant_delete",
    "session_revision_transition",
    "training_start",
    "update_profile",
)
