# Generated by Django 4.0.4 on 2026-08-20 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_release_organization_models'),
        ('iatrain_motion', '0005_alter_jointangledefinition_component'),
        ('iatrain_biomechanics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('free_weight', 'Pes lliure'), ('elastic', 'Resistència elàstica'), ('support', 'Suport o superfície'), ('machine', 'Màquina'), ('suspension', 'Suspensió'), ('other', 'Altres')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('catalog_id', 'category', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=220)),
                ('kind', models.CharField(choices=[('family', "Família d'exercicis"), ('variant', 'Variant executable')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('catalog_id', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExerciseChangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('human', 'Persona'), ('llm', 'Model de llenguatge'), ('system', 'Sistema')], max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposada'), ('accepted', 'Acceptada'), ('rejected', 'Rebutjada'), ('applied', 'Aplicada')], default='proposed', max_length=20)),
                ('rationale', models.TextField()),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_change_proposals', to='core.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_exercise_change_proposals', to='core.person')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ExerciseGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_code', models.CharField(max_length=100)),
                ('field_path', models.CharField(max_length=220)),
                ('severity', models.CharField(choices=[('required', 'Obligatori'), ('recommended', 'Recomanat')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Obert'), ('proposed', 'Amb proposta'), ('resolved', 'Resolt'), ('dismissed', 'Descartat')], default='open', max_length=20)),
                ('detected_by', models.CharField(choices=[('system', 'Validador del sistema'), ('llm', 'Model de llenguatge'), ('human', 'Persona')], max_length=20)),
                ('description', models.TextField()),
                ('schema_version', models.CharField(default='exercise_completeness_v1', max_length=60)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('revision_id', 'severity', 'requirement_code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExercisePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_index', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('phase_type', models.CharField(choices=[('setup', 'Preparació'), ('active', 'Activa'), ('transition', 'Transició'), ('hold', 'Manteniment'), ('recovery', 'Retorn o recuperació')], max_length=20)),
                ('intent', models.CharField(choices=[('produce', 'Produir el moviment'), ('assist', 'Assistir el moviment'), ('control', 'Controlar o frenar'), ('hold', 'Mantenir posició'), ('reposition', 'Reposicionar')], max_length=20)),
                ('description', models.TextField()),
                ('is_key_phase', models.BooleanField(default=False)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_exercise_phases', to='core.person')),
            ],
            options={
                'ordering': ('revision_id', 'sequence_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExerciseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('modality', models.CharField(choices=[('strength', 'Força'), ('power', 'Potència'), ('muscular_endurance', 'Resistència muscular'), ('motor_control', 'Control motor'), ('mobility', 'Mobilitat'), ('warm_up', 'Escalfament')], max_length=30)),
                ('execution_type', models.CharField(choices=[('dynamic', 'Dinàmic'), ('isometric', 'Isomètric'), ('mixed', 'Mixt')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Inicial'), ('intermediate', 'Intermedi'), ('advanced', 'Avançat')], max_length=20)),
                ('laterality', models.CharField(choices=[('bilateral', 'Bilateral'), ('unilateral', 'Unilateral'), ('alternating', 'Alternant'), ('not_applicable', 'No aplicable')], max_length=20)),
                ('kinetic_chain', models.CharField(choices=[('open', 'Cadena oberta'), ('closed', 'Cadena tancada'), ('mixed', 'Mixta'), ('unspecified', 'No especificada')], max_length=20)),
                ('movement_pattern', models.CharField(choices=[('squat', 'Esquat'), ('hinge', 'Frontissa de maluc'), ('horizontal_push', 'Empenta horitzontal'), ('vertical_push', 'Empenta vertical'), ('horizontal_pull', 'Tracció horitzontal'), ('vertical_pull', 'Tracció vertical'), ('ankle_dominant', 'Dominant de turmell'), ('trunk_control', 'Control del tronc'), ('locomotion', 'Locomoció'), ('other', 'Altres')], max_length=30)),
                ('description', models.TextField()),
                ('setup', models.TextField()),
                ('execution', models.TextField()),
                ('coaching_cues', models.TextField()),
                ('safety_notes', models.TextField(blank=True, default='')),
                ('requires_equipment', models.BooleanField(default=False)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_exercise_revisions', to='core.person')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='iatrain_exercises.exercise')),
                ('last_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_exercise_revisions', to='core.person')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='iatrain_exercises.exerciserevision')),
            ],
            options={
                'ordering': ('exercise_id', '-revision_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExerciseProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'Afegir'), ('replace', 'Substituir'), ('remove', 'Retirar'), ('link', 'Crear connexió')], max_length=20)),
                ('target_path', models.CharField(max_length=220)),
                ('proposed_value', models.JSONField()),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendent'), ('accepted', 'Acceptat'), ('rejected', 'Rebutjat'), ('applied', 'Aplicat')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='iatrain_exercises.exercisechangeproposal')),
                ('resolves_gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_items', to='iatrain_exercises.exercisegap')),
            ],
            options={
                'ordering': ('proposal_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExercisePhaseMuscleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Contribuïdor principal'), ('secondary', 'Contribuïdor secundari'), ('stabilizer', 'Estabilitzador')], max_length=20)),
                ('expected_contraction', models.CharField(choices=[('concentric', 'Concèntrica esperada'), ('eccentric', 'Excèntrica esperada'), ('isometric', 'Isomètrica esperada'), ('variable', 'Variable segons execució'), ('indeterminate', 'No determinada')], default='indeterminate', max_length=20)),
                ('verification_state', models.CharField(choices=[('confirmed', "Confirmat per l'autor"), ('inferred', 'Inferit pel sistema'), ('pending', 'Pendent de confirmar')], default='pending', max_length=20)),
                ('rationale', models.TextField()),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('action_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercise_phase_roles', to='iatrain_biomechanics.muscleactionfunction')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_phase_muscle_roles', to='iatrain_motion.motionconcept')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_roles', to='iatrain_exercises.exercisephase')),
                ('stabilization_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercise_phase_roles', to='iatrain_biomechanics.musclestabilizationfunction')),
            ],
            options={
                'ordering': ('phase_id', 'role', 'muscle_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExercisePhaseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Acció principal'), ('supporting', 'Acció de suport')], max_length=20)),
                ('laterality', models.CharField(choices=[('bilateral', 'Bilateral'), ('left', 'Esquerra'), ('right', 'Dreta'), ('alternating', 'Alternant'), ('unspecified', 'No especificada')], default='unspecified', max_length=20)),
                ('verification_state', models.CharField(choices=[('confirmed', "Confirmat per l'autor"), ('inferred', 'Inferit'), ('pending', 'Pendent de confirmar')], default='pending', max_length=20)),
                ('rationale', models.TextField()),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_phase_actions', to='iatrain_motion.motionconcept')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='iatrain_exercises.exercisephase')),
            ],
            options={
                'ordering': ('phase_id', 'role', 'action_id', 'id'),
            },
        ),
        migrations.AddField(
            model_name='exercisephase',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='iatrain_exercises.exerciserevision'),
        ),
        migrations.CreateModel(
            name='ExerciseObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.CharField(choices=[('max_strength', 'Força màxima'), ('hypertrophy', 'Hipertròfia'), ('muscular_endurance', 'Resistència muscular'), ('power', 'Potència'), ('motor_control', 'Control motor'), ('mobility', 'Mobilitat'), ('preparation', 'Preparació o escalfament')], max_length=30)),
                ('priority', models.CharField(choices=[('primary', 'Principal'), ('secondary', 'Secundari')], max_length=20)),
                ('rationale', models.TextField()),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='iatrain_exercises.exerciserevision')),
            ],
            options={
                'ordering': ('revision_id', 'priority', 'objective', 'id'),
            },
        ),
        migrations.AddField(
            model_name='exercisegap',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='iatrain_exercises.exerciserevision'),
        ),
        migrations.CreateModel(
            name='ExerciseEquipmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.CharField(choices=[('required', 'Necessari'), ('optional', 'Opcional'), ('substitute', 'Alternativa')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_requirements', to='iatrain_exercises.equipment')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requirements', to='iatrain_exercises.exerciserevision')),
            ],
            options={
                'ordering': ('revision_id', 'requirement', 'equipment_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExerciseConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('requirement', "Requisit d'execució"), ('precaution', 'Precaució'), ('limitation', "Limitació de l'exercici")], max_length=20)),
                ('severity', models.CharField(choices=[('information', 'Informativa'), ('important', 'Important'), ('critical', 'Crítica')], max_length=20)),
                ('statement', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='iatrain_exercises.exerciserevision')),
            ],
            options={
                'ordering': ('revision_id', 'kind', 'code', 'id'),
            },
        ),
        migrations.AddField(
            model_name='exercisechangeproposal',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_proposals', to='iatrain_exercises.exerciserevision'),
        ),
        migrations.CreateModel(
            name='ExerciseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('personal', 'Personal')], default='personal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_catalogs', to='core.person')),
            ],
            options={
                'ordering': ('owner_id', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='iatrain_exercises.exercisecatalog'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exercises', to='core.person'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='iatrain_exercises.exercise'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_definitions', to='iatrain_exercises.exercisecatalog'),
        ),
        migrations.AddIndex(
            model_name='exerciserevision',
            index=models.Index(fields=['exercise', 'editorial_status'], name='exercise_revision_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciserevision',
            index=models.Index(fields=['movement_pattern', 'modality', 'editorial_status'], name='exercise_revision_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='exerciserevision',
            constraint=models.UniqueConstraint(fields=('exercise', 'revision_number'), name='exercise_revision_uniq_number'),
        ),
        migrations.AddConstraint(
            model_name='exerciserevision',
            constraint=models.UniqueConstraint(condition=models.Q(('editorial_status', 'validated')), fields=('exercise',), name='exercise_revision_one_validated'),
        ),
        migrations.AddConstraint(
            model_name='exerciserevision',
            constraint=models.CheckConstraint(check=models.Q(('supersedes', django.db.models.expressions.F('id')), _negated=True), name='exercise_revision_no_self_supersede'),
        ),
        migrations.AddIndex(
            model_name='exerciseproposalitem',
            index=models.Index(fields=['proposal', 'status'], name='exercise_proposal_item_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisephasemusclerole',
            index=models.Index(fields=['muscle', 'role'], name='exercise_phase_muscle_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisephasemusclerole',
            constraint=models.UniqueConstraint(fields=('phase', 'muscle', 'role'), name='exercise_phase_muscle_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exercisephasemusclerole',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action_function__isnull', False), ('stabilization_function__isnull', True)), models.Q(('action_function__isnull', True), ('stabilization_function__isnull', False)), _connector='OR'), name='exercise_muscle_exactly_one_basis'),
        ),
        migrations.AddIndex(
            model_name='exercisephaseaction',
            index=models.Index(fields=['action', 'role'], name='exercise_phase_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisephaseaction',
            constraint=models.UniqueConstraint(fields=('phase', 'action', 'laterality'), name='exercise_phase_action_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exercisephase',
            constraint=models.UniqueConstraint(fields=('revision', 'sequence_index'), name='exercise_phase_uniq_sequence'),
        ),
        migrations.AddConstraint(
            model_name='exercisephase',
            constraint=models.UniqueConstraint(fields=('revision', 'code'), name='exercise_phase_uniq_code'),
        ),
        migrations.AddConstraint(
            model_name='exerciseobjective',
            constraint=models.UniqueConstraint(fields=('revision', 'objective'), name='exercise_objective_uniq'),
        ),
        migrations.AddIndex(
            model_name='exercisegap',
            index=models.Index(fields=['revision', 'status'], name='exercise_gap_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisegap',
            constraint=models.UniqueConstraint(fields=('revision', 'requirement_code', 'schema_version'), name='exercise_gap_uniq_requirement'),
        ),
        migrations.AddConstraint(
            model_name='exerciseequipmentrequirement',
            constraint=models.UniqueConstraint(fields=('revision', 'equipment'), name='exercise_equipment_requirement_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exerciseconstraint',
            constraint=models.UniqueConstraint(fields=('revision', 'code'), name='exercise_constraint_uniq_code'),
        ),
        migrations.AddIndex(
            model_name='exercisechangeproposal',
            index=models.Index(fields=['revision', 'status'], name='exercise_proposal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisecatalog',
            index=models.Index(fields=['owner', 'is_active'], name='exercise_catalog_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisecatalog',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='exercise_catalog_uniq_owner_code'),
        ),
        migrations.AddConstraint(
            model_name='exercisecatalog',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.expressions.F('owner'), name='exercise_catalog_uniq_owner_name'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['catalog', 'kind', 'is_active'], name='exercise_catalog_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('catalog', 'code'), name='exercise_uniq_catalog_code'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.expressions.F('catalog'), name='exercise_uniq_catalog_name'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'family'), ('parent__isnull', True)), models.Q(('kind', 'variant'), ('parent__isnull', False)), _connector='OR'), name='exercise_kind_parent_consistent'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('catalog', 'code'), name='exercise_equipment_uniq_code'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.expressions.F('catalog'), name='exercise_equipment_uniq_name'),
        ),
    ]
