# Generated by Django 4.0.4 on 2026-08-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iatrain_exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseobjective',
            name='objective',
            field=models.CharField(choices=[('strength', 'Força general'), ('max_strength', 'Força màxima'), ('hypertrophy', 'Hipertròfia'), ('muscular_endurance', 'Resistència muscular'), ('power', 'Potència'), ('motor_control', 'Control motor'), ('mobility', 'Mobilitat'), ('preparation', 'Preparació o escalfament')], max_length=30),
        ),
    ]
