# Generated by Django 4.2 on 2026-08-21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iatrain_exercises", "0002_alter_exerciseobjective_objective"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExercisePrescriptionGuideline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("population_stage", models.CharField(choices=[("all", "Totes"), ("child", "Infància"), ("adolescent", "Adolescència"), ("adult", "Edat adulta"), ("older_adult", "Adult gran")], default="all", max_length=20)),
                ("experience_level", models.CharField(choices=[("all", "Tots"), ("novice", "Inicial"), ("intermediate", "Intermedi"), ("advanced", "Avançat")], default="all", max_length=20)),
                ("objective", models.CharField(choices=[("strength", "Força general"), ("max_strength", "Força màxima"), ("hypertrophy", "Hipertròfia"), ("muscular_endurance", "Resistència muscular"), ("power", "Potència"), ("motor_control", "Control motor"), ("mobility", "Mobilitat"), ("preparation", "Preparació o escalfament")], max_length=30)),
                ("block_role", models.CharField(choices=[("all", "Totes"), ("preparation", "Preparació"), ("main", "Principal"), ("complementary", "Complementari"), ("recovery", "Recuperació"), ("assessment", "Avaluació")], default="all", max_length=20)),
                ("dose_mode", models.CharField(choices=[("repetitions", "Repeticions"), ("duration", "Durada"), ("hold", "Manteniment"), ("distance", "Distància"), ("assisted", "Assistida")], max_length=20)),
                ("min_sets", models.PositiveSmallIntegerField(default=1)),
                ("default_sets", models.PositiveSmallIntegerField(default=2)),
                ("max_sets", models.PositiveSmallIntegerField(default=3)),
                ("min_repetitions", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("default_repetitions", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_repetitions", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("min_duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("default_duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("max_duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("min_rest_seconds", models.PositiveSmallIntegerField(default=0)),
                ("default_rest_seconds", models.PositiveSmallIntegerField(default=60)),
                ("max_rest_seconds", models.PositiveSmallIntegerField(default=180)),
                ("min_rpe", models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ("max_rpe", models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ("setup_duration_seconds", models.PositiveSmallIntegerField(default=20)),
                ("seconds_per_repetition", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ("mechanical_impact", models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("neuromuscular_load", models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("metabolic_load", models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("coordinative_load", models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("quality_stop_rule", models.TextField(blank=True, default="")),
                ("evidence_type", models.CharField(choices=[("position_stand", "Posicionament professional"), ("consensus", "Consens"), ("systematic_review", "Revisió sistemàtica"), ("professional_standard", "Estàndard professional"), ("expert_review", "Revisió experta"), ("observed_data", "Dades observades")], max_length=30)),
                ("source_title", models.CharField(max_length=240)),
                ("source_url", models.URLField(blank=True, default="")),
                ("source_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("rationale", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prescription_guidelines", to="iatrain_exercises.exerciserevision")),
            ],
            options={
                "ordering": ("revision_id", "population_stage", "experience_level", "objective", "block_role"),
            },
        ),
        migrations.AddConstraint(
            model_name="exerciseprescriptionguideline",
            constraint=models.UniqueConstraint(fields=("revision", "population_stage", "experience_level", "objective", "block_role", "dose_mode"), name="exercise_prescription_guideline_uniq"),
        ),
    ]
