SEED_VERSION = "private_exercise_examples_v1"


EQUIPMENT = (
    {"code": "barbell", "name": "Barra", "category": "free_weight"},
    {"code": "bench", "name": "Banc", "category": "support"},
    {"code": "elastic_band", "name": "Banda elàstica", "category": "elastic"},
    {"code": "mat", "name": "Matalàs fi", "category": "support"},
)


EXERCISES = (
    {
        "family": ("hip_thrust", "Hip thrust"),
        "variant": ("barbell_hip_thrust", "Hip thrust amb barra"),
        "revision": {
            "modality": "strength", "execution_type": "dynamic", "difficulty": "intermediate",
            "laterality": "bilateral", "kinetic_chain": "closed", "movement_pattern": "hinge",
            "description": "Extensió de maluc amb l'esquena superior recolzada i una barra sobre la pelvis.",
            "setup": "Recolza la zona escapular al banc, situa la barra protegida sobre la pelvis i planta els peus a terra.",
            "execution": "Eleva la pelvis fins a una extensió de maluc controlada, mantén breument i torna sense perdre la posició del tronc.",
            "coaching_cues": "Empeny el terra, mantén les costelles controlades i acaba el moviment amb el maluc, no amb hiperextensió lumbar.",
            "safety_notes": "La càrrega i el rang s'han d'adaptar al control disponible; la descripció no substitueix una valoració clínica.",
            "requires_equipment": True,
        },
        "equipment": (("barbell", "required"), ("bench", "required")),
        "objectives": (("max_strength", "primary"), ("hypertrophy", "secondary")),
        "constraints": (("stable_bench", "requirement", "important", "El banc ha de ser estable i no desplaçar-se."),),
        "phases": (
            {"code": "raise", "name": "Elevació", "type": "active", "intent": "produce", "key": True,
             "description": "La pelvis s'eleva mitjançant extensió de maluc.",
             "actions": (("hip_extension", "primary"),),
             "muscles": (("gluteus_maximus", "primary", "gluteus_maximus__hip_extension__general", "action", "concentric"),)},
            {"code": "top_hold", "name": "Manteniment superior", "type": "hold", "intent": "hold", "key": True,
             "description": "Es manté breument la posició superior amb el maluc estès.",
             "actions": (),
             "muscles": (("gluteus_maximus", "primary", "gluteus_maximus__hip_extension__general", "action", "isometric"),)},
            {"code": "lower", "name": "Descens", "type": "recovery", "intent": "control", "key": True,
             "description": "La pelvis baixa de manera controlada cap a flexió de maluc.",
             "actions": (("hip_flexion", "primary"),),
             "muscles": (("gluteus_maximus", "primary", "gluteus_maximus__hip_extension__general", "action", "eccentric"),)},
        ),
    },
    {
        "family": ("squat", "Esquat"),
        "variant": ("bodyweight_squat", "Esquat amb pes corporal"),
        "revision": {
            "modality": "motor_control", "execution_type": "dynamic", "difficulty": "beginner",
            "laterality": "bilateral", "kinetic_chain": "closed", "movement_pattern": "squat",
            "description": "Patró bilateral d'esquat sense càrrega externa, amb flexió i extensió coordinades de maluc, genoll i turmell.",
            "setup": "Dempeus, peus estables i separació adaptada a la persona.",
            "execution": "Descendeix controlant maluc, genolls i turmells; després torna a la posició inicial mantenint l'equilibri.",
            "coaching_cues": "Mantén els peus en contacte, acompanya la direcció dels genolls i conserva el tronc controlat.",
            "safety_notes": "El rang ha de correspondre a la mobilitat i el control disponibles.",
            "requires_equipment": False,
        },
        "equipment": (),
        "objectives": (("motor_control", "primary"), ("muscular_endurance", "secondary")),
        "constraints": (("controlled_range", "requirement", "important", "Utilitza només un rang que es pugui controlar sense perdre l'equilibri."),),
        "phases": (
            {"code": "descent", "name": "Descens", "type": "active", "intent": "control", "key": True,
             "description": "Flexió coordinada de maluc i genoll amb flexió dorsal de turmell.",
             "actions": (("hip_flexion", "primary"), ("knee_flexion", "primary"), ("ankle_dorsiflexion", "supporting")),
             "muscles": (("gluteus_maximus", "primary", "gluteus_maximus__hip_extension__general", "action", "eccentric"), ("vastus_lateralis", "secondary", "vastus_lateralis__knee_extension__general", "action", "eccentric"))},
            {"code": "ascent", "name": "Ascens", "type": "active", "intent": "produce", "key": True,
             "description": "Extensió coordinada de maluc i genoll fins a tornar dempeus.",
             "actions": (("hip_extension", "primary"), ("knee_extension", "primary"), ("ankle_plantarflexion", "supporting")),
             "muscles": (("gluteus_maximus", "primary", "gluteus_maximus__hip_extension__general", "action", "concentric"), ("vastus_lateralis", "secondary", "vastus_lateralis__knee_extension__general", "action", "concentric"))},
        ),
    },
    {
        "family": ("push_up", "Flexió de braços"),
        "variant": ("floor_push_up", "Flexió de braços a terra"),
        "revision": {
            "modality": "strength", "execution_type": "dynamic", "difficulty": "intermediate",
            "laterality": "bilateral", "kinetic_chain": "closed", "movement_pattern": "horizontal_push",
            "description": "Empenta horitzontal amb pes corporal i mans fixes a terra.",
            "setup": "Posició de planxa alta amb mans estables, cos alineat i suport sobre mans i peus.",
            "execution": "Baixa el cos flexionant els colzes i torna a empènyer el terra fins a la posició inicial.",
            "coaching_cues": "Mou el cos com una unitat, controla les escàpules i evita perdre la posició del tronc.",
            "safety_notes": "Ajusta l'alçada de suport si no es pot mantenir el control corporal.",
            "requires_equipment": False,
        },
        "equipment": (("mat", "optional"),),
        "objectives": (("strength", "primary"), ("motor_control", "secondary")),
        "constraints": (("trunk_alignment", "requirement", "important", "Cal mantenir un control global del tronc durant totes les fases."),),
        "phases": (
            {"code": "lower", "name": "Descens", "type": "active", "intent": "control", "key": True,
             "description": "El cos baixa amb flexió de colze i abducció horitzontal d'espatlla.",
             "actions": (("elbow_flexion", "primary"), ("shoulder_horizontal_abduction", "primary")),
             "muscles": (("triceps_brachii", "primary", "triceps_brachii__elbow_extension__general", "action", "eccentric"), ("pectoralis_major", "primary", "pectoralis_major__shoulder_horizontal_adduction__general", "action", "eccentric"), ("serratus_anterior", "stabilizer", "serratus_anterior_scapular_control", "stabilization", "isometric"))},
            {"code": "press", "name": "Empenta", "type": "active", "intent": "produce", "key": True,
             "description": "El cos s'allunya del terra amb extensió de colze i adducció horitzontal d'espatlla.",
             "actions": (("elbow_extension", "primary"), ("shoulder_horizontal_adduction", "primary")),
             "muscles": (("triceps_brachii", "primary", "triceps_brachii__elbow_extension__general", "action", "concentric"), ("pectoralis_major", "primary", "pectoralis_major__shoulder_horizontal_adduction__general", "action", "concentric"), ("serratus_anterior", "stabilizer", "serratus_anterior_scapular_control", "stabilization", "isometric"))},
        ),
    },
    {
        "family": ("calf_raise", "Elevació de talons"),
        "variant": ("bilateral_bodyweight_calf_raise", "Elevació bilateral de talons"),
        "revision": {
            "modality": "strength", "execution_type": "dynamic", "difficulty": "beginner",
            "laterality": "bilateral", "kinetic_chain": "closed", "movement_pattern": "ankle_dominant",
            "description": "Flexió plantar bilateral en suport dempeus utilitzant el pes corporal.",
            "setup": "Dempeus amb els avantpeus estables i un suport proper si cal equilibri.",
            "execution": "Eleva els talons, mantén breument i baixa de forma controlada.",
            "coaching_cues": "Mantén la pressió distribuïda sobre l'avantpeu i evita desplaçaments laterals.",
            "safety_notes": "Adapta el rang si el control del turmell és limitat.",
            "requires_equipment": False,
        },
        "equipment": (),
        "objectives": (("strength", "primary"), ("motor_control", "secondary")),
        "constraints": (("balance_support", "precaution", "information", "Utilitza un suport estable si l'equilibri limita l'execució."),),
        "phases": (
            {"code": "raise", "name": "Elevació", "type": "active", "intent": "produce", "key": True,
             "description": "Els talons s'eleven mitjançant flexió plantar.",
             "actions": (("ankle_plantarflexion", "primary"),),
             "muscles": (("gastrocnemius", "primary", "gastrocnemius__ankle_plantarflexion__general", "action", "concentric"), ("soleus", "primary", "soleus__ankle_plantarflexion__general", "action", "concentric"))},
            {"code": "lower", "name": "Descens", "type": "recovery", "intent": "control", "key": True,
             "description": "Els talons baixen cap a flexió dorsal controlada.",
             "actions": (("ankle_dorsiflexion", "primary"),),
             "muscles": (("gastrocnemius", "primary", "gastrocnemius__ankle_plantarflexion__general", "action", "eccentric"), ("soleus", "primary", "soleus__ankle_plantarflexion__general", "action", "eccentric"))},
        ),
    },
    {
        "family": ("front_plank", "Planxa frontal"),
        "variant": ("forearm_front_plank", "Planxa frontal sobre avantbraços"),
        "revision": {
            "modality": "motor_control", "execution_type": "isometric", "difficulty": "beginner",
            "laterality": "bilateral", "kinetic_chain": "closed", "movement_pattern": "trunk_control",
            "description": "Manteniment isomètric global amb suport sobre avantbraços i peus.",
            "setup": "Situa avantbraços i peus a terra i organitza el cos en una posició estable.",
            "execution": "Mantén la posició durant el temps prescrit sense perdre el control del tronc ni de la cintura escapular.",
            "coaching_cues": "Respira, mantén la pelvis controlada i empeny suaument el terra amb els avantbraços.",
            "safety_notes": "Finalitza la sèrie quan no es pugui conservar la posició definida.",
            "requires_equipment": False,
        },
        "equipment": (("mat", "optional"),),
        "objectives": (("motor_control", "primary"), ("muscular_endurance", "secondary")),
        "constraints": (("quality_before_duration", "requirement", "important", "La durada no ha de superar la capacitat de mantenir la posició acordada."),),
        "phases": (
            {"code": "hold", "name": "Manteniment", "type": "hold", "intent": "hold", "key": True,
             "description": "Es manté el tronc i la cintura escapular sota suport estable.",
             "actions": (),
             "muscles": (("transversus_abdominis", "stabilizer", "transversus_abdominis_trunk_postural", "stabilization", "isometric"), ("serratus_anterior", "stabilizer", "serratus_anterior_scapular_control", "stabilization", "isometric"))},
        ),
    },
    {
        "family": ("shoulder_external_rotation", "Rotació externa d'espatlla"),
        "variant": ("band_shoulder_external_rotation", "Rotació externa d'espatlla amb banda"),
        "revision": {
            "modality": "strength", "execution_type": "dynamic", "difficulty": "beginner",
            "laterality": "unilateral", "kinetic_chain": "open", "movement_pattern": "other",
            "description": "Rotació externa unilateral d'espatlla contra resistència elàstica.",
            "setup": "Ancora la banda, mantén el colze flexionat prop del tronc i situa l'avantbraç davant del cos.",
            "execution": "Rota l'espatlla cap enfora sense separar el colze i torna lentament a la posició inicial.",
            "coaching_cues": "Mantén el tronc quiet, controla l'escàpula i utilitza un rang sense compensacions.",
            "safety_notes": "La resistència ha de permetre una execució sense dolor ni compensació visible.",
            "requires_equipment": True,
        },
        "equipment": (("elastic_band", "required"),),
        "objectives": (("strength", "primary"), ("motor_control", "secondary")),
        "constraints": (("stable_anchor", "requirement", "critical", "La banda ha d'estar fixada a un punt d'ancoratge segur."),),
        "phases": (
            {"code": "rotate_out", "name": "Rotació externa", "type": "active", "intent": "produce", "key": True,
             "description": "L'húmer rota externament contra la tensió de la banda.",
             "actions": (("shoulder_external_rotation", "primary"),),
             "muscles": (("infraspinatus", "primary", "infraspinatus__shoulder_external_rotation__general", "action", "concentric"),)},
            {"code": "return", "name": "Retorn", "type": "recovery", "intent": "control", "key": True,
             "description": "L'espatlla retorna cap a rotació interna de manera controlada.",
             "actions": (("shoulder_internal_rotation", "primary"),),
             "muscles": (("infraspinatus", "primary", "infraspinatus__shoulder_external_rotation__general", "action", "eccentric"),)},
        ),
    },
)
