# Generated by Django 4.2 on 2026-08-03 15:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(help_text='Tipus extensible: skill, technical_component, error, exercise, quality, risk, goal…', max_length=60)),
                ('discipline', models.CharField(default='trampoline', max_length=80)),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Atributs extensibles amb significat documentat; no hi desis relacions entre conceptes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_knowledge_concepts', to='core.person')),
            ],
            options={
                'ordering': ('discipline', 'kind', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('purpose', models.TextField(blank=True, default='')),
                ('discipline', models.CharField(default='trampoline', help_text='Vocabulari curt i estable, per exemple: trampoline, dmt, tumbling o general.', max_length=80)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Esborrany'), ('active', 'Actiu'), ('closed', 'Tancat'), ('archived', 'Arxivat')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensions petites i no crítiques; no substitueix camps de domini nous.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athletes', models.ManyToManyField(blank=True, help_text='Un sol gimnasta per a context individual; diversos per a un context compartit.', related_name='training_contexts', to='core.person')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_contexts', to='core.organization')),
                ('responsible_coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_training_contexts', to='core.person')),
            ],
            options={
                'ordering': ('-valid_from', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(help_text='Tipus dirigit extensible: requires, progresses_to, corrects, conditions, trains…', max_length=60)),
                ('rationale', models.TextField(blank=True, default='')),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validada'), ('retired', 'Retirada')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_knowledge_relations', to='core.person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='iatrain.knowledgeconcept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='iatrain.knowledgeconcept')),
            ],
            options={
                'ordering': ('source_id', 'relation_type', 'target_id'),
            },
        ),
        migrations.CreateModel(
            name='AthleteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('competency', 'Competència'), ('learning', 'Aprenentatge'), ('strength', 'Fortalesa'), ('difficulty', 'Dificultat'), ('fear_block', 'Por o bloqueig'), ('limitation', 'Limitació'), ('note', 'Nota')], default='note', max_length=30)),
                ('narrative', models.TextField()),
                ('evidence', models.TextField(blank=True, default='', help_text='Fets observables que sostenen la nota; no és una justificació generada automàticament.')),
                ('status', models.CharField(choices=[('observed', 'Observat'), ('in_progress', 'En progrés'), ('stable', 'Estable'), ('no_longer_current', 'No vigent')], default='observed', max_length=30)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, help_text='Confiança entre 0 i 1; deixa-la buida si no es pot estimar honestament.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('intensity', models.PositiveSmallIntegerField(blank=True, help_text='Intensitat opcional entre 1 i 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_observations', to='core.person')),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_athlete_observations', to='core.person')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_observations', to='iatrain.knowledgeconcept')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='iatrain.athleteobservation')),
                ('training_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='iatrain.trainingcontext')),
            ],
            options={
                'ordering': ('-observed_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='trainingcontext',
            index=models.Index(fields=['responsible_coach', 'status', 'valid_from'], name='iatrain_ctx_coach_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcontext',
            index=models.Index(fields=['organization', 'status'], name='iatrain_ctx_org_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcontext',
            index=models.Index(fields=['discipline', 'status'], name='iatrain_ctx_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingcontext',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='iatrain_context_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['source', 'relation_type', 'editorial_status'], name='iatrain_rel_source_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['target', 'editorial_status'], name='iatrain_rel_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerelation',
            constraint=models.CheckConstraint(check=models.Q(('source', models.F('target')), _negated=True), name='iatrain_relation_distinct_nodes'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='iatrain_relation_uniq_edge'),
        ),
        migrations.AddIndex(
            model_name='knowledgeconcept',
            index=models.Index(fields=['discipline', 'kind', 'editorial_status'], name='iatrain_concept_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeconcept',
            index=models.Index(fields=['authored_by', 'created_at'], name='iatrain_concept_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeconcept',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('kind'), models.F('discipline'), name='iatrain_concept_uniq_name'),
        ),
        migrations.AddIndex(
            model_name='athleteobservation',
            index=models.Index(fields=['athlete', 'status', 'observed_at'], name='iatrain_obs_athlete_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteobservation',
            index=models.Index(fields=['training_context', 'observed_at'], name='iatrain_obs_context_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteobservation',
            index=models.Index(fields=['concept', 'category'], name='iatrain_obs_concept_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteobservation',
            index=models.Index(fields=['authored_by', 'observed_at'], name='iatrain_obs_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='athleteobservation',
            constraint=models.CheckConstraint(check=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='iatrain_obs_confidence_valid'),
        ),
        migrations.AddConstraint(
            model_name='athleteobservation',
            constraint=models.CheckConstraint(check=models.Q(('intensity__isnull', True), models.Q(('intensity__gte', 1), ('intensity__lte', 5)), _connector='OR'), name='iatrain_obs_intensity_valid'),
        ),
    ]
