# Generated by Django 4.2 on 2026-08-04 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_training_relations(apps, schema_editor):
    LegacyRelation = apps.get_model("core", "CoachAthleteRelation")
    AthleteProfile = apps.get_model("iatrain", "AthleteProfile")
    CoachProfile = apps.get_model("iatrain", "CoachProfile")
    Relation = apps.get_model("iatrain", "CoachAthleteRelation")

    for legacy in LegacyRelation.objects.all().iterator():
        coach_profile, _ = CoachProfile.objects.get_or_create(person_id=legacy.coach_id)
        athlete_profile, _ = AthleteProfile.objects.get_or_create(person_id=legacy.athlete_id)
        Relation.objects.create(
            coach_profile=coach_profile,
            athlete_profile=athlete_profile,
            organization_id=legacy.organization_id,
            function=legacy.function,
            can_view_profile=legacy.can_view_profile,
            can_view_training=legacy.can_view_training,
            can_edit_training=legacy.can_edit_training,
            can_view_health_data=legacy.can_view_health_data,
            start_date=legacy.start_date,
            end_date=legacy.end_date,
            is_active=legacy.is_active,
            notes=legacy.notes,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personclaiminvitation_personmergerecord_and_more'),
        ('iatrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Configuració pròpia del mode gimnasta; només dades petites i estructurades.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to='core.person')),
            ],
            options={
                'ordering': ('person__last_name', 'person__first_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Configuració pròpia del mode entrenador; només dades petites i estructurades.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='core.person')),
            ],
            options={
                'ordering': ('person__last_name', 'person__first_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CoachAthleteRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('primary', 'Entrenador/a principal'), ('assistant', 'Entrenador/a assistent'), ('physical', 'Preparació física'), ('choreographer', 'Coreografia'), ('other', 'Altres')], default='primary', max_length=20)),
                ('can_view_profile', models.BooleanField(default=True)),
                ('can_view_training', models.BooleanField(default=True)),
                ('can_edit_training', models.BooleanField(default=False)),
                ('can_view_health_data', models.BooleanField(default=False, help_text="Permís sensible que s'ha de concedir explícitament.")),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_relations', to='iatrain.athleteprofile')),
                ('coach_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_relations', to='iatrain.coachprofile')),
                ('organization', models.ForeignKey(blank=True, help_text="Organització en què s'aplica la relació; buit si és global.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_relationships', to='core.organization')),
            ],
            options={
                'ordering': ('athlete_profile_id', 'coach_profile_id', 'function'),
            },
        ),
        migrations.AddIndex(
            model_name='coachathleterelation',
            index=models.Index(fields=['coach_profile', 'is_active'], name='iatrain_rel_coach_idx'),
        ),
        migrations.AddIndex(
            model_name='coachathleterelation',
            index=models.Index(fields=['athlete_profile', 'is_active'], name='iatrain_rel_athlete_idx'),
        ),
        migrations.AddIndex(
            model_name='coachathleterelation',
            index=models.Index(fields=['organization', 'is_active'], name='iatrain_rel_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='iatrain_relation_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.CheckConstraint(check=models.Q(('can_edit_training', False), ('can_view_training', True), _connector='OR'), name='iatrain_relation_edit_view'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.CheckConstraint(check=models.Q(('can_view_health_data', False), ('can_view_profile', True), _connector='OR'), name='iatrain_relation_health_profile'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('coach_profile', 'athlete_profile', 'organization', 'function'), name='iatrain_relation_uniq_context'),
        ),
        migrations.AddConstraint(
            model_name='coachathleterelation',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('coach_profile', 'athlete_profile', 'function'), name='iatrain_relation_uniq_global'),
        ),
        migrations.RunPython(migrate_training_relations, migrations.RunPython.noop),
    ]
