# Generated by Django 4.2 on 2026-08-04 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import iatrain.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_person_last_name'),
        ('iatrain', '0002_athleteprofile_coachprofile_coachathleterelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('extracted_facts', models.JSONField(blank=True, default=list, help_text='Fets encara no formalitzats sobre el grup, com horaris, material o objectius.', validators=[iatrain.models.validate_extracted_facts])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('organization__name', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='extracted_facts',
            field=models.JSONField(blank=True, default=list, help_text='Fets extrets del llenguatge natural, amb font, confiança i estat; no substitueixen els camps de domini confirmats.', validators=[iatrain.models.validate_extracted_facts]),
        ),
        migrations.CreateModel(
            name='TrainingGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='iatrain.athleteprofile')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='iatrain.traininggroup')),
            ],
            options={
                'ordering': ('training_group_id', 'athlete_profile_id', '-start_date', 'id'),
            },
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='training_groups', through='iatrain.TrainingGroupMembership', to='iatrain.athleteprofile'),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_groups', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='traininggroupmembership',
            index=models.Index(fields=['training_group', 'is_active'], name='iatrain_grp_member_group_idx'),
        ),
        migrations.AddIndex(
            model_name='traininggroupmembership',
            index=models.Index(fields=['athlete_profile', 'is_active'], name='iatrain_grp_member_ath_idx'),
        ),
        migrations.AddConstraint(
            model_name='traininggroupmembership',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='iatrain_group_membership_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='traininggroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('training_group', 'athlete_profile'), name='iatrain_group_member_unique_active'),
        ),
        migrations.AddIndex(
            model_name='traininggroup',
            index=models.Index(fields=['organization', 'is_active'], name='iatrain_group_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='traininggroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='iatrain_group_name_org_ci_uniq'),
        ),
    ]
