# Generated by Django 4.0.4 on 2026-08-07 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_person_last_name'),
        ('iatrain', '0004_traininggroup_managing_coaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, default='', max_length=240)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gyms', to='iatrain.coachprofile')),
            ],
            options={
                'ordering': ('name', 'location', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GymOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='iatrain.gym')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_links', to='core.organization')),
            ],
            options={
                'ordering': ('organization__name', 'gym__name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GymEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('equipment_type', models.CharField(choices=[('trampoline', 'Trampolí'), ('double_mini', 'Doble minitrampolí'), ('tumbling_track', 'Pista de tumbling'), ('mat', 'Matalàs'), ('spotting_platform', 'Plataforma de seguretat'), ('harness', 'Cinturó o arnès'), ('conditioning', 'Preparació física'), ('other', 'Altres')], default='other', max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('limited', 'Ús limitat'), ('maintenance', 'En manteniment'), ('unavailable', 'No disponible')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='iatrain.gym')),
            ],
            options={
                'ordering': ('gym_id', 'equipment_type', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='gym',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='training_gyms', through='iatrain.GymOrganization', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='gymorganization',
            index=models.Index(fields=['organization', 'is_active'], name='iatrain_gym_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='gymorganization',
            constraint=models.UniqueConstraint(fields=('gym', 'organization'), name='iatrain_gym_org_uniq'),
        ),
        migrations.AddIndex(
            model_name='gymequipment',
            index=models.Index(fields=['gym', 'availability'], name='iatrain_gym_equipment_idx'),
        ),
        migrations.AddConstraint(
            model_name='gymequipment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.expressions.F('gym'), name='iatrain_gym_equipment_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['is_active', 'name'], name='iatrain_gym_active_idx'),
        ),
    ]
