# Generated by Django 4.2 on 2026-08-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_release_organization_models'),
        ('iatrain', '0006_retarget_organization_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transverse_quarters', models.PositiveSmallIntegerField()),
                ('transverse_direction', models.CharField(choices=[('unknown', 'No resolta'), ('none', 'Sense rotació transversal'), ('forward', 'Endavant'), ('backward', 'Enrere')], default='unknown', max_length=20)),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_element_rotations', to='core.person')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_profile', to='iatrain.knowledgeconcept')),
            ],
            options={
                'ordering': ('element_id',),
            },
        ),
        migrations.CreateModel(
            name='ElementRotationSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveSmallIntegerField()),
                ('longitudinal_half_turns', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='iatrain.elementrotation')),
            ],
            options={
                'ordering': ('rotation_id', 'sequence_index'),
            },
        ),
        migrations.CreateModel(
            name='ElementNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(default='fig_numeric', max_length=40)),
                ('scheme_version', models.CharField(blank=True, default='legacy', max_length=40)),
                ('raw_notation', models.CharField(max_length=80)),
                ('normalized_notation', models.CharField(blank=True, default='', max_length=80)),
                ('parse_status', models.CharField(choices=[('parsed', 'Interpretada'), ('ambiguous', 'Ambigua'), ('invalid', 'No vàlida')], default='parsed', max_length=20)),
                ('is_abbreviated', models.BooleanField(default=False)),
                ('direction_source', models.CharField(choices=[('explicit', 'Explícita'), ('inferred', 'Inferida'), ('unknown', 'No resolta')], default='unknown', max_length=20)),
                ('position_source', models.CharField(choices=[('explicit', 'Explícita'), ('inferred', 'Inferida'), ('unknown', 'No resolta')], default='unknown', max_length=20)),
                ('position_symbol', models.CharField(blank=True, default='', max_length=1)),
                ('parse_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_element_notations', to='core.person')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_notations', to='iatrain.knowledgeconcept')),
                ('rotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notations', to='iatrain.elementrotation')),
            ],
            options={
                'ordering': ('element_id', 'scheme', 'raw_notation', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='elementrotationsegment',
            constraint=models.CheckConstraint(check=models.Q(('sequence_index__gte', 1)), name='iatrain_rotation_segment_index'),
        ),
        migrations.AddConstraint(
            model_name='elementrotationsegment',
            constraint=models.UniqueConstraint(fields=('rotation', 'sequence_index'), name='iatrain_rotation_segment_uniq'),
        ),
        migrations.AddIndex(
            model_name='elementrotation',
            index=models.Index(fields=['editorial_status', 'transverse_quarters'], name='iatrain_rotation_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='elementnotation',
            index=models.Index(fields=['scheme', 'parse_status'], name='iatrain_notation_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='elementnotation',
            constraint=models.UniqueConstraint(fields=('element', 'scheme', 'raw_notation'), name='iatrain_element_notation_uniq'),
        ),
    ]
