# Generated by Django 4.2 on 2026-08-20 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_move_content_types'),
        ('core', '0007_release_organization_models'),
        ('iatrain_exercises', '0002_alter_exerciseobjective_objective'),
        ('iatrain', '0008_editorial_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_index', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=160)),
                ('block_role', models.CharField(choices=[('preparation', 'Preparació'), ('main', 'Principal'), ('complementary', 'Complementari'), ('recovery', 'Recuperació'), ('assessment', 'Avaluació')], max_length=20)),
                ('domain', models.CharField(choices=[('physical', 'Físic'), ('technical', 'Tècnic'), ('mixed', 'Mixt'), ('general', 'General')], max_length=20)),
                ('execution_mode', models.CharField(choices=[('sequential', 'Seqüencial'), ('circuit', 'Circuit'), ('stations', 'Estacions'), ('superset', 'Supersèrie'), ('parallel', 'Paral·lel')], default='sequential', max_length=20)),
                ('planned_duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transition_duration_seconds', models.PositiveSmallIntegerField(default=0)),
                ('objective', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_optional', models.BooleanField(default=False)),
                ('rounds', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('rest_between_rounds_seconds', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('session_revision_id', 'sequence_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('expected_duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('discipline', models.CharField(choices=[('trampoline', 'Trampolí'), ('dmt', 'Doble minitrampolí'), ('tumbling', 'Tumbling'), ('general', 'General')], max_length=20)),
                ('session_scope', models.CharField(choices=[('individual', 'Individual'), ('group', 'Grup')], max_length=20)),
                ('lifecycle_status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En curs'), ('completed', 'Completada'), ('cancelled', 'Cancel·lada')], default='scheduled', max_length=20)),
                ('creation_origin', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generada'), ('imported', 'Importada')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_training_sessions', to='core.person')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='iatrain.gym')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='organizations.organization')),
                ('responsible_coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_training_sessions', to='iatrain.coachprofile')),
                ('training_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='iatrain.traininggroup')),
            ],
            options={
                'ordering': ('-scheduled_start', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Esborrany'), ('proposed', 'Proposada'), ('approved', 'Aprovada'), ('superseded', 'Substituïda'), ('rejected', 'Rebutjada')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('general_objective', models.TextField(blank=True, default='')),
                ('planned_duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creation_origin', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generada'), ('imported', 'Importada')], default='manual', max_length=20)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_training_session_revisions', to='core.person')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_training_session_revisions', to='core.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='iatrain.trainingsession')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='iatrain.trainingsessionrevision')),
            ],
            options={
                'ordering': ('session_id', '-revision_number', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_index', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item_type', models.CharField(choices=[('physical_exercise', 'Exercici físic'), ('instruction', 'Instrucció'), ('recovery', 'Recuperació'), ('break', 'Pausa'), ('technical_task', 'Tasca tècnica'), ('technical_element', 'Element tècnic'), ('sequence', 'Seqüència'), ('assessment', 'Avaluació')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('instructions', models.TextField(blank=True, default='')),
                ('coaching_cues', models.TextField(blank=True, default='')),
                ('planned_duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rest_after_seconds', models.PositiveSmallIntegerField(default=0)),
                ('selection_rationale', models.TextField(blank=True, default='')),
                ('is_optional', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='iatrain.trainingblock')),
            ],
            options={
                'ordering': ('block_id', 'sequence_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'No iniciada'), ('in_progress', 'En curs'), ('completed', 'Completada'), ('aborted', 'Interrompuda')], default='not_started', max_length=20)),
                ('general_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='iatrain.trainingsessionrevision')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='iatrain.trainingsession')),
                ('supervised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_training_executions', to='iatrain.coachprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('completed', 'Completat'), ('partial', 'Parcial'), ('skipped', 'Omes'), ('substituted', 'Substituït'), ('stopped', 'Aturat')], max_length=20)),
                ('actual_sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_repetitions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_load_unit', models.CharField(blank=True, choices=[('kg', 'Quilograms'), ('percent_bodyweight', '% del pes corporal'), ('other', 'Altres')], default='', max_length=30)),
                ('perceived_exertion', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('execution_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pain_response', models.CharField(choices=[('none', 'Sense dolor'), ('reported', 'Dolor comunicat'), ('stopped', 'Aturat per dolor')], default='none', max_length=20)),
                ('athlete_feedback', models.TextField(blank=True, default='')),
                ('coach_feedback', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_item_results', to='iatrain.athleteprofile')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_results', to='iatrain.trainingsessionexecution')),
                ('exercise_revision_performed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_training_results', to='iatrain_exercises.exerciserevision')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_training_item_results', to='core.person')),
                ('session_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_results', to='iatrain.trainingsessionitem')),
            ],
            options={
                'ordering': ('execution_id', 'session_item_id', 'athlete_profile_id'),
            },
        ),
        migrations.AddField(
            model_name='trainingblock',
            name='session_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='iatrain.trainingsessionrevision'),
        ),
        migrations.CreateModel(
            name='SessionParticipantPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_participation', models.CharField(choices=[('full', 'Completa'), ('partial', 'Parcial'), ('optional', 'Opcional')], default='full', max_length=20)),
                ('individual_objective', models.TextField(blank=True, default='')),
                ('planning_notes', models.TextField(blank=True, default='')),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_training_sessions', to='iatrain.athleteprofile')),
                ('session_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_plans', to='iatrain.trainingsessionrevision')),
            ],
            options={
                'ordering': ('session_revision_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SessionItemAthleteAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sets', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('repetitions', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('load_unit', models.CharField(blank=True, choices=[('kg', 'Quilograms'), ('percent_bodyweight', '% del pes corporal'), ('other', 'Altres')], default='', max_length=30)),
                ('intensity_metric', models.CharField(blank=True, choices=[('none', 'Sense mètrica'), ('rpe', 'RPE'), ('rir', 'RIR'), ('percent_1rm', '% 1RM'), ('technical_quality', 'Qualitat tècnica'), ('bodyweight', 'Pes corporal'), ('assisted', 'Assistida')], default='', max_length=30)),
                ('intensity_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rest_between_sets_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('adaptation_notes', models.TextField(blank=True, default='')),
                ('rationale', models.TextField(blank=True, default='')),
                ('participant_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_adjustments', to='iatrain.sessionparticipantplan')),
                ('replacement_exercise_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_adjustments', to='iatrain_exercises.exerciserevision')),
                ('session_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_adjustments', to='iatrain.trainingsessionitem')),
            ],
            options={
                'ordering': ('session_item_id', 'participant_plan_id'),
            },
        ),
        migrations.CreateModel(
            name='SessionItemAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('trigger', models.CharField(choices=[('equipment_unavailable', 'Material no disponible'), ('difficulty_too_high', 'Dificultat excessiva'), ('pain_or_restriction', 'Dolor o restricció'), ('group_logistics', 'Logística de grup'), ('coach_decision', "Decisió de l'entrenador")], max_length=30)),
                ('rationale', models.TextField(blank=True, default='')),
                ('exercise_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_alternatives', to='iatrain_exercises.exerciserevision')),
                ('session_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='iatrain.trainingsessionitem')),
            ],
            options={
                'ordering': ('session_item_id', 'priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SessionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('physical', 'Físic'), ('technical', 'Tècnic'), ('recovery', 'Recuperació'), ('assessment', 'Avaluació'), ('general', 'General')], max_length=20)),
                ('code', models.SlugField(max_length=80)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('primary', 'Principal'), ('secondary', 'Secundari'), ('optional', 'Opcional')], max_length=20)),
                ('source', models.CharField(choices=[('coach', 'Entrenador'), ('plan', 'Planificació'), ('assessment', 'Avaluació'), ('system', 'Sistema')], default='coach', max_length=20)),
                ('rationale', models.TextField(blank=True, default='')),
                ('session_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='iatrain.trainingsessionrevision')),
            ],
            options={
                'ordering': ('session_revision_id', 'priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('partial', 'Parcial'), ('excused', 'Justificada')], max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_attendance', to='iatrain.athleteprofile')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='iatrain.trainingsessionexecution')),
            ],
            options={
                'ordering': ('execution_id', 'athlete_profile_id'),
            },
        ),
        migrations.CreateModel(
            name='PhysicalExercisePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_mode', models.CharField(choices=[('repetitions', 'Repeticions'), ('duration', 'Durada'), ('distance', 'Distància'), ('hold', 'Manteniment'), ('assisted', 'Assistida')], max_length=20)),
                ('sets', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('repetitions', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('distance_unit', models.CharField(blank=True, choices=[('m', 'Metres'), ('km', 'Quilòmetres')], default='', max_length=10)),
                ('load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('load_unit', models.CharField(blank=True, choices=[('kg', 'Quilograms'), ('percent_bodyweight', '% del pes corporal'), ('other', 'Altres')], default='', max_length=30)),
                ('intensity_metric', models.CharField(choices=[('none', 'Sense mètrica'), ('rpe', 'RPE'), ('rir', 'RIR'), ('percent_1rm', '% 1RM'), ('technical_quality', 'Qualitat tècnica'), ('bodyweight', 'Pes corporal'), ('assisted', 'Assistida')], default='none', max_length=30)),
                ('intensity_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tempo_eccentric_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tempo_pause_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tempo_concentric_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('concentric_intent', models.CharField(choices=[('controlled', 'Controlada'), ('fast', 'Ràpida'), ('explosive', 'Explosiva')], default='controlled', max_length=20)),
                ('rest_between_sets_seconds', models.PositiveSmallIntegerField(default=0)),
                ('execution_notes', models.TextField(blank=True, default='')),
                ('exercise_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_prescriptions', to='iatrain_exercises.exerciserevision')),
                ('session_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_prescription', to='iatrain.trainingsessionitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='trainingsessionrevision',
            index=models.Index(fields=['session', 'status'], name='iatrain_session_rev_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionrevision',
            constraint=models.UniqueConstraint(fields=('session', 'revision_number'), name='iatrain_session_rev_uniq_number'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('session',), name='iatrain_session_one_approved_rev'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionrevision',
            constraint=models.CheckConstraint(check=models.Q(('supersedes', models.F('id')), _negated=True), name='iatrain_session_rev_no_self_sup'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionitem',
            constraint=models.UniqueConstraint(fields=('block', 'sequence_index'), name='iatrain_session_item_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionexecution',
            index=models.Index(fields=['status', 'started_at'], name='iatrain_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['organization', 'scheduled_start'], name='iatrain_session_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['responsible_coach', 'scheduled_start'], name='iatrain_session_coach_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingitemresult',
            index=models.Index(fields=['athlete_profile', 'recorded_at'], name='iatrain_result_athlete_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingitemresult',
            constraint=models.UniqueConstraint(fields=('execution', 'session_item', 'athlete_profile'), name='iatrain_item_result_uniq'),
        ),
        migrations.AddConstraint(
            model_name='trainingblock',
            constraint=models.UniqueConstraint(fields=('session_revision', 'sequence_index'), name='iatrain_session_block_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipantplan',
            constraint=models.UniqueConstraint(fields=('session_revision', 'athlete_profile'), name='iatrain_plan_participant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sessionitemathleteadjustment',
            constraint=models.UniqueConstraint(fields=('session_item', 'participant_plan'), name='iatrain_item_athlete_adjust_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sessionitemalternative',
            constraint=models.UniqueConstraint(fields=('session_item', 'exercise_revision'), name='iatrain_item_alternative_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sessiongoal',
            constraint=models.UniqueConstraint(fields=('session_revision', 'domain', 'code'), name='iatrain_session_goal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendance',
            constraint=models.UniqueConstraint(fields=('execution', 'athlete_profile'), name='iatrain_execution_attendance_uniq'),
        ),
    ]
