# Generated by Django 4.2 on 2026-08-20 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def scope_existing_observations(apps, schema_editor):
    AthleteObservation = apps.get_model('iatrain', 'AthleteObservation')
    observations = AthleteObservation.objects.filter(
        organization__isnull=True,
        training_context__organization__isnull=False,
    ).values_list('pk', 'training_context__organization_id')
    for observation_id, organization_id in observations.iterator():
        AthleteObservation.objects.filter(pk=observation_id).update(
            organization_id=organization_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_release_organization_models'),
        ('iatrain_motion', '0005_alter_jointangledefinition_component'),
        ('organizations', '0002_move_content_types'),
        ('iatrain', '0009_trainingblock_trainingsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pain', 'Dolor'), ('discomfort', 'Molèstia'), ('injury', 'Lesió comunicada'), ('medical_restriction', 'Restricció mèdica'), ('load_tolerance', 'Tolerància de càrrega'), ('readiness', 'Disponibilitat'), ('other', 'Altres')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('narrative', models.TextField()),
                ('evidence', models.TextField(blank=True, default='')),
                ('laterality', models.CharField(choices=[('not_applicable', 'No aplicable'), ('bilateral', 'Bilateral'), ('right', 'Dreta'), ('left', 'Esquerra')], default='not_applicable', max_length=20)),
                ('severity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('training_impact', models.CharField(choices=[('none', 'Sense impacte declarat'), ('monitor', 'Monitorar'), ('modify', 'Modificar'), ('avoid', 'Evitar'), ('stop', 'No entrenar')], default='monitor', max_length=20)),
                ('source', models.CharField(choices=[('athlete_report', 'Informació del gimnasta'), ('coach_observation', "Observació de l'entrenador"), ('session_response', 'Resposta durant una sessió'), ('clinical_document', 'Document clínic aportat'), ('imported', 'Importada')], max_length=30)),
                ('status', models.CharField(choices=[('proposed', 'Pendent de confirmació'), ('confirmed', 'Confirmada'), ('resolved', 'Resolta'), ('rejected', 'Descartada'), ('superseded', 'Substituïda')], default='proposed', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='iatrain.athleteprofile')),
                ('body_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athlete_conditions', to='iatrain_motion.motionconcept')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_athlete_conditions', to='core.person')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athlete_conditions', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_athlete_conditions', to='core.person')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='iatrain.athletecondition')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AthleteInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trend', 'Tendència'), ('progress', 'Progrés'), ('tolerance', 'Tolerància'), ('preference', 'Preferència'), ('risk_signal', 'Senyal de risc'), ('hypothesis', 'Hipòtesi'), ('data_gap', "Manca d'informació")], max_length=20)),
                ('statement', models.TextField()),
                ('rationale', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('proposed', 'Proposada'), ('confirmed', 'Confirmada'), ('rejected', 'Descartada'), ('superseded', 'Substituïda'), ('expired', 'Caducada')], default='proposed', max_length=20)),
                ('evidence_window_start', models.DateTimeField(blank=True, null=True)),
                ('evidence_window_end', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insights', to='iatrain.athleteprofile')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_athlete_insights', to='core.person')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athlete_insights', to='organizations.organization')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triggered_athlete_insights', to='core.person')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='athleteobservation',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Abast de privacitat; buit només per a observacions personals globals.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athlete_observations', to='organizations.organization'),
        ),
        migrations.RunPython(scope_existing_observations, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AthleteSportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('trampoline', 'Trampolí'), ('dmt', 'Doble minitrampolí'), ('tumbling', 'Tumbling'), ('general', 'Preparació general')], max_length=20)),
                ('level_code', models.CharField(blank=True, default='', help_text='Vocabulari extensible de nivell; no pressuposa una escala universal.', max_length=80)),
                ('training_started_on', models.DateField(blank=True, null=True)),
                ('preferred_laterality', models.CharField(choices=[('unknown', 'No determinada'), ('right', 'Dreta'), ('left', 'Esquerra'), ('mixed', 'Mixta')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sport_profiles', to='iatrain.athleteprofile')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_athlete_sport_profiles', to='core.person')),
            ],
            options={
                'ordering': ('athlete_profile_id', 'discipline'),
            },
        ),
        migrations.CreateModel(
            name='AthleteMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('anthropometry', 'Antropometria'), ('strength', 'Força'), ('power', 'Potència'), ('mobility', 'Mobilitat'), ('motor_control', 'Control motor'), ('endurance', 'Resistència'), ('recovery', 'Recuperació'), ('workload', 'Càrrega'), ('other', 'Altres')], max_length=30)),
                ('metric_code', models.CharField(max_length=100)),
                ('metric_label', models.CharField(max_length=180)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=40)),
                ('side', models.CharField(choices=[('not_applicable', 'No aplicable'), ('bilateral', 'Bilateral'), ('right', 'Dreta'), ('left', 'Esquerra')], default='not_applicable', max_length=20)),
                ('protocol', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('assessment', 'Valoració'), ('device', 'Dispositiu'), ('training_result', "Resultat d'entrenament"), ('athlete_report', 'Informació del gimnasta'), ('imported', 'Importada')], max_length=30)),
                ('uncertainty', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Vàlida'), ('invalidated', 'Invalidada')], default='valid', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='iatrain.athleteprofile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athlete_measurements', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_athlete_measurements', to='core.person')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='iatrain.athletemeasurement')),
            ],
            options={
                'ordering': ('-measured_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AthleteInsightEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insight_evidence_links', to='iatrain.athletecondition')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='iatrain.athleteinsight')),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insight_evidence_links', to='iatrain.athletemeasurement')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insight_evidence_links', to='iatrain.athleteobservation')),
                ('training_item_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insight_evidence_links', to='iatrain.trainingitemresult')),
            ],
            options={
                'ordering': ('insight_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='athletesportprofile',
            constraint=models.UniqueConstraint(fields=('athlete_profile', 'discipline'), name='iatrain_athlete_sport_profile_uniq'),
        ),
        migrations.AddIndex(
            model_name='athletemeasurement',
            index=models.Index(fields=['athlete_profile', 'metric_code', 'measured_at'], name='iatrain_measure_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='athletemeasurement',
            index=models.Index(fields=['organization', 'measured_at'], name='iatrain_measure_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='athletemeasurement',
            constraint=models.CheckConstraint(check=models.Q(('supersedes', models.F('id')), _negated=True), name='iatrain_measure_no_self_supersede'),
        ),
        migrations.AddConstraint(
            model_name='athleteinsightevidence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('condition__isnull', True), ('measurement__isnull', True), ('observation__isnull', False), ('training_item_result__isnull', True)), models.Q(('condition__isnull', True), ('measurement__isnull', False), ('observation__isnull', True), ('training_item_result__isnull', True)), models.Q(('condition__isnull', False), ('measurement__isnull', True), ('observation__isnull', True), ('training_item_result__isnull', True)), models.Q(('condition__isnull', True), ('measurement__isnull', True), ('observation__isnull', True), ('training_item_result__isnull', False)), _connector='OR'), name='iatrain_insight_evidence_one_source'),
        ),
        migrations.AddIndex(
            model_name='athleteinsight',
            index=models.Index(fields=['athlete_profile', 'status', 'kind'], name='iatrain_insight_current_idx'),
        ),
        migrations.AddIndex(
            model_name='athletecondition',
            index=models.Index(fields=['athlete_profile', 'status', 'started_at'], name='iatrain_condition_current_idx'),
        ),
        migrations.AddIndex(
            model_name='athletecondition',
            index=models.Index(fields=['organization', 'status'], name='iatrain_condition_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='athletecondition',
            constraint=models.CheckConstraint(check=models.Q(('severity__isnull', True), models.Q(('severity__gte', 1), ('severity__lte', 5)), _connector='OR'), name='iatrain_condition_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='athletecondition',
            constraint=models.CheckConstraint(check=models.Q(('supersedes', models.F('id')), _negated=True), name='iatrain_condition_no_self_sup'),
        ),
    ]
