# Generated by Django 4.2 on 2026-08-21

from django.db import migrations, models
import django.db.models.deletion
import iatrain.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_release_organization_models"),
        ("iatrain", "0010_athletecondition_athleteinsight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymequipment",
            name="catalog_equipment_codes",
            field=models.JSONField(blank=True, default=list, help_text="Codis del material dels catàlegs d'exercicis equivalent a aquest inventari. El motor també intenta resoldre equivalències pel nom.", validators=[iatrain.models.validate_catalog_equipment_codes]),
        ),
        migrations.CreateModel(
            name="BlockGenerationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("processing", "Generant"), ("proposed", "Proposta preparada"), ("applied", "Afegida a la sessió"), ("discarded", "Descartada"), ("failed", "No completada")], default="processing", max_length=20)),
                ("prompt", models.TextField()),
                ("refinement_instruction", models.TextField(blank=True, default="")),
                ("interpretation_payload", models.JSONField(blank=True, default=dict)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("proposal_payload", models.JSONField(blank=True, default=dict)),
                ("source_references", models.JSONField(blank=True, default=list)),
                ("model_name", models.CharField(blank=True, default="", max_length=120)),
                ("prompt_version", models.CharField(default="1.0", max_length=40)),
                ("engine_version", models.CharField(default="1.0", max_length=40)),
                ("contract_version", models.CharField(default="1.0", max_length=40)),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applied_block", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="generation_run", to="iatrain.trainingblock")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_block_generation_runs", to="core.person")),
                ("parent_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="refinements", to="iatrain.blockgenerationrun")),
                ("session_revision", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="block_generation_runs", to="iatrain.trainingsessionrevision")),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.AddIndex(
            model_name="blockgenerationrun",
            index=models.Index(fields=["session_revision", "status", "created_at"], name="iatrain_block_gen_status_idx"),
        ),
    ]
