# Generated by Django 4.2 on 2026-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iatrain', '0017_blockparticipantassignment_condition_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionitemathleteadjustment',
            name='station_remainder_action',
            field=models.CharField(blank=True, choices=[('rest', 'Recuperació'), ('reset', 'Recol·locació tècnica'), ('monitor', 'Monitoratge')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='blockgenerationrun',
            name='status',
            field=models.CharField(choices=[('processing', 'Generant'), ('awaiting_decision', 'Esperant decisió'), ('proposed', 'Proposta preparada'), ('review_required', 'Requereix revisió'), ('applied', 'Afegida a la sessió'), ('discarded', 'Descartada'), ('failed', 'No completada')], default='processing', max_length=20),
        ),
    ]
