# Generated by Django 4.2 on 2026-08-20 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iatrain_motion', '0004_alter_motionconcept_kind_and_more'),
        ('core', '0007_release_organization_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomechanicalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140, unique=True)),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('kinetic_chain', models.CharField(choices=[('unspecified', 'No especificada'), ('open', 'Cadena oberta'), ('closed', 'Cadena tancada'), ('either', 'Aplicable a ambdues')], default='unspecified', max_length=20)),
                ('loading_conditions', models.JSONField(blank=True, default=dict)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_authored', to='core.person')),
                ('last_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_validated', to='core.person')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EvidenceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('anatomy_ontology', 'Ontologia anatòmica'), ('textbook', 'Manual o llibre de referència'), ('peer_reviewed', 'Publicació revisada per parells'), ('professional_consensus', 'Consens professional'), ('computational_model', 'Model computacional'), ('other', 'Altres')], max_length=40)),
                ('identifier_type', models.CharField(choices=[('doi', 'DOI'), ('isbn', 'ISBN'), ('url', 'URL'), ('ontology', 'Identificador ontològic'), ('other', 'Altres')], max_length=30)),
                ('identifier', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, default='')),
                ('citation', models.TextField(blank=True, default='')),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_biomechanical_evidence_references', to='core.person')),
            ],
            options={
                'ordering': ('title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MuscleActionFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140, unique=True)),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_class', models.CharField(choices=[('major', 'Contribució mecànica principal'), ('supporting', 'Contribució de suport'), ('variable', 'Contribució dependent del context'), ('unspecified', 'No jerarquitzada')], default='unspecified', max_length=20)),
                ('statement', models.TextField()),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('limitations', models.TextField(blank=True, default='')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muscular_contributors', to='iatrain_motion.motionconcept')),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_authored', to='core.person')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_action_functions', to='iatrain_biomechanics.biomechanicalcontext')),
            ],
            options={
                'ordering': ('muscle_id', 'action_id', 'context_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MuscleStabilizationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('supports', 'Sosté'), ('qualifies', 'Matisa o limita'), ('contradicts', 'Contradiu')], default='supports', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iatrain_biomechanics.evidencereference')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleStabilizationFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140, unique=True)),
                ('editorial_status', models.CharField(choices=[('draft', 'Esborrany'), ('validated', 'Validat'), ('retired', 'Retirat')], default='draft', max_length=20)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stabilization_type', models.CharField(choices=[('joint_centering', 'Centratge articular'), ('segment_control', 'Control segmentari'), ('co_contraction', 'Cocontracció'), ('force_transfer', 'Transferència de força'), ('postural', 'Control postural')], max_length=30)),
                ('statement', models.TextField()),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('limitations', models.TextField(blank=True, default='')),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_authored', to='core.person')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscle_stabilization_functions', to='iatrain_biomechanics.biomechanicalcontext')),
                ('evidence', models.ManyToManyField(related_name='muscle_stabilization_functions', through='iatrain_biomechanics.MuscleStabilizationEvidence', to='iatrain_biomechanics.evidencereference')),
                ('last_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_validated', to='core.person')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biomechanical_stabilization_functions', to='iatrain_motion.motionconcept')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='iatrain_biomechanics.musclestabilizationfunction')),
                ('target_joint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscular_joint_stabilizers', to='iatrain_motion.motionconcept')),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muscular_segment_stabilizers', to='iatrain_motion.motionconcept')),
            ],
            options={
                'ordering': ('muscle_id', 'stabilization_type', 'id'),
            },
        ),
        migrations.AddField(
            model_name='musclestabilizationevidence',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='iatrain_biomechanics.musclestabilizationfunction'),
        ),
        migrations.CreateModel(
            name='MuscleActionFunctionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('supports', 'Sosté'), ('qualifies', 'Matisa o limita'), ('contradicts', 'Contradiu')], default='supports', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iatrain_biomechanics.evidencereference')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='iatrain_biomechanics.muscleactionfunction')),
            ],
        ),
        migrations.AddField(
            model_name='muscleactionfunction',
            name='evidence',
            field=models.ManyToManyField(related_name='muscle_action_functions', through='iatrain_biomechanics.MuscleActionFunctionEvidence', to='iatrain_biomechanics.evidencereference'),
        ),
        migrations.AddField(
            model_name='muscleactionfunction',
            name='last_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_validated', to='core.person'),
        ),
        migrations.AddField(
            model_name='muscleactionfunction',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biomechanical_action_functions', to='iatrain_motion.motionconcept'),
        ),
        migrations.AddField(
            model_name='muscleactionfunction',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='iatrain_biomechanics.muscleactionfunction'),
        ),
        migrations.CreateModel(
            name='ContextAngleConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140)),
                ('minimum_radians', models.FloatField(blank=True, null=True)),
                ('maximum_radians', models.FloatField(blank=True, null=True)),
                ('effect', models.CharField(choices=[('applicable', 'Aplicable'), ('enhanced', 'Contribució augmentada'), ('reduced', 'Contribució reduïda'), ('reversed', 'Efecte mecànic invertit')], default='applicable', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('angle_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biomechanical_context_constraints', to='iatrain_motion.jointangledefinition')),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_biomechanical_angle_constraints', to='core.person')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angle_constraints', to='iatrain_biomechanics.biomechanicalcontext')),
            ],
            options={
                'ordering': ('context_id', 'code', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='musclestabilizationfunction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_joint__isnull', False), ('target_segment__isnull', True)), models.Q(('target_joint__isnull', True), ('target_segment__isnull', False)), _connector='OR'), name='biomech_stabilization_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='musclestabilizationfunction',
            constraint=models.CheckConstraint(check=models.Q(('supersedes', models.F('id')), _negated=True), name='biomech_stabilization_no_self_supersede'),
        ),
        migrations.AddConstraint(
            model_name='musclestabilizationfunction',
            constraint=models.UniqueConstraint(condition=models.Q(('context__isnull', True), ('target_joint__isnull', False)), fields=('muscle', 'target_joint', 'stabilization_type'), name='biomech_stabilization_uniq_general_joint'),
        ),
        migrations.AddConstraint(
            model_name='musclestabilizationfunction',
            constraint=models.UniqueConstraint(condition=models.Q(('context__isnull', True), ('target_segment__isnull', False)), fields=('muscle', 'target_segment', 'stabilization_type'), name='biomech_stabilization_uniq_general_segment'),
        ),
        migrations.AddConstraint(
            model_name='musclestabilizationevidence',
            constraint=models.UniqueConstraint(fields=('function', 'evidence'), name='biomech_stabilization_evidence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='muscleactionfunctionevidence',
            constraint=models.UniqueConstraint(fields=('function', 'evidence'), name='biomech_action_evidence_uniq'),
        ),
        migrations.AddIndex(
            model_name='muscleactionfunction',
            index=models.Index(fields=['muscle', 'editorial_status'], name='biomech_action_muscle_idx'),
        ),
        migrations.AddIndex(
            model_name='muscleactionfunction',
            index=models.Index(fields=['action', 'editorial_status'], name='biomech_action_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='muscleactionfunction',
            constraint=models.UniqueConstraint(condition=models.Q(('context__isnull', True)), fields=('muscle', 'action'), name='biomech_action_function_uniq_general'),
        ),
        migrations.AddConstraint(
            model_name='muscleactionfunction',
            constraint=models.UniqueConstraint(condition=models.Q(('context__isnull', False)), fields=('muscle', 'action', 'context'), name='biomech_action_function_uniq_context'),
        ),
        migrations.AddConstraint(
            model_name='muscleactionfunction',
            constraint=models.CheckConstraint(check=models.Q(('supersedes', models.F('id')), _negated=True), name='biomech_action_function_no_self_supersede'),
        ),
        migrations.AddConstraint(
            model_name='evidencereference',
            constraint=models.UniqueConstraint(fields=('identifier_type', 'identifier'), name='biomech_evidence_uniq_identifier'),
        ),
        migrations.AddConstraint(
            model_name='contextangleconstraint',
            constraint=models.UniqueConstraint(fields=('context', 'code'), name='biomech_context_angle_uniq_code'),
        ),
        migrations.AddConstraint(
            model_name='biomechanicalcontext',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='biomech_context_uniq_name'),
        ),
    ]
