# Generated by Django 4.2 on 2026-01-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_i_cognoms', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=120, null=True)),
                ('entitat', models.CharField(blank=True, max_length=120, null=True)),
                ('document', models.CharField(blank=True, max_length=32, null=True)),
                ('sexe', models.CharField(blank=True, max_length=50, null=True)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcions', to='competicions_trampoli.competicio')),
            ],
            options={
                'ordering': ['categoria', 'subcategoria', 'entitat', 'sexe', 'data_naixement', 'nom_i_cognoms'],
            },
        ),
        migrations.AddIndex(
            model_name='inscripcio',
            index=models.Index(fields=['competicio', 'categoria', 'subcategoria'], name='competicion_competi_99019d_idx'),
        ),
    ]
