# Generated by Django 4.2 on 2026-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcio',
            name='ordre_sortida',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
