# Generated by Django 4.2 on 2026-01-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0002_inscripcio_ordre_sortida'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcio',
            name='group_by_default',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
