# Generated by Django 4.2 on 2026-01-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0003_inscripcio_group_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicio',
            name='group_by_default',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
