# Generated by Django 4.2 on 2026-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0004_competicio_group_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcio',
            name='grup',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
