# Generated by Django 4.2 on 2026-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0005_inscripcio_grup'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicio',
            name='tipus',
            field=models.CharField(choices=[('natacio', 'Natació'), ('patinatge', 'Patinatge'), ('trampoli', 'Gimnàstica trampolí'), ('artistica', 'Gimnàstica artística')], default='trampoli', max_length=20),
        ),
    ]
