# Generated by Django 4.2 on 2026-01-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0006_competicio_tipus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrampoliConfiguracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jutges_execucio', models.PositiveSmallIntegerField(default=3)),
                ('nombre_jutges_dificultat', models.PositiveSmallIntegerField(default=1)),
                ('pes_execucio', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('pes_dificultat', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('sistema_classificacio', models.CharField(default='suma', max_length=50)),
                ('competicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cfg_trampoli', to='competicions_trampoli.competicio')),
            ],
        ),
        migrations.CreateModel(
            name='TrampoliNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_execucio', models.JSONField(blank=True, default=list)),
                ('dificultat', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('tof', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('hdc', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('penalitzacio', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_trampoli', to='competicions_trampoli.competicio')),
                ('inscripcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_trampoli', to='competicions_trampoli.inscripcio')),
            ],
            options={
                'unique_together': {('competicio', 'inscripcio')},
            },
        ),
    ]
