# Generated by Django 4.2 on 2026-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0007_trampoliconfiguracio_trampolinota'),
    ]

    operations = [
        migrations.AddField(
            model_name='trampolinota',
            name='crash_execucio',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trampolinota',
            name='execucio_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
