# Generated by Django 4.2 on 2026-01-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0008_trampolinota_crash_execucio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='mode_execucio',
            field=models.CharField(choices=[('salts', 'Per salts (S1..S11)'), ('manual', 'Execució global manual')], default='salts', max_length=10),
        ),
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='mostrar_dificultat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='mostrar_hd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='mostrar_penalitzacio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='mostrar_salts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='mostrar_tof',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='mostrar_total',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trampolinota',
            name='execucio_manual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
