# Generated by Django 4.2 on 2026-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0009_trampoliconfiguracio_mode_execucio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicio',
            name='tab_merges',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='mostrar_dificultat',
            field=models.BooleanField(default=True, verbose_name='Mostrar Dificultat'),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='mostrar_hd',
            field=models.BooleanField(default=True, verbose_name='Mostrar HD'),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='mostrar_penalitzacio',
            field=models.BooleanField(default=True, verbose_name='Mostrar Penalització'),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='mostrar_salts',
            field=models.BooleanField(default=True, verbose_name='Mostrar Notes per Salts'),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='mostrar_tof',
            field=models.BooleanField(default=True, verbose_name='Mostrar TOF'),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='mostrar_total',
            field=models.BooleanField(default=True, verbose_name='Mostrar Total'),
        ),
    ]
