# Generated by Django 4.2 on 2026-01-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0010_competicio_tab_merges_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trampolinota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='nombre_exercicis',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Nombre d'exercicis de cada gimnasta"),
        ),
        migrations.AddField(
            model_name='trampolinota',
            name='exercici',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='trampolinota',
            constraint=models.UniqueConstraint(fields=('competicio', 'inscripcio', 'exercici'), name='uniq_nota_trampoli_per_exercici'),
        ),
    ]
