# Generated by Django 4.2 on 2026-01-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0011_alter_trampolinota_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=60)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CompeticioAparell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('nombre_elements', models.PositiveSmallIntegerField(default=11)),
                ('te_execucio', models.BooleanField(default=True)),
                ('te_dificultat', models.BooleanField(default=True)),
                ('te_tof', models.BooleanField(default=True)),
                ('te_hd', models.BooleanField(default=True)),
                ('te_penalitzacio', models.BooleanField(default=True)),
                ('mode_execucio', models.CharField(choices=[('salts', 'Per elements'), ('manual', 'Execució global manual')], default='salts', max_length=10)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='trampolinota',
            name='uniq_nota_trampoli_per_exercici',
        ),
        migrations.AddField(
            model_name='competicioaparell',
            name='aparell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competicio_cfg', to='competicions_trampoli.aparell'),
        ),
        migrations.AddField(
            model_name='competicioaparell',
            name='competicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aparells_cfg', to='competicions_trampoli.competicio'),
        ),
        migrations.AddField(
            model_name='trampolinota',
            name='comp_aparell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='competicions_trampoli.competicioaparell'),
        ),
        migrations.AddConstraint(
            model_name='trampolinota',
            constraint=models.UniqueConstraint(fields=('competicio', 'inscripcio', 'exercici', 'comp_aparell'), name='uniq_nota_trampoli_per_exercici_aparell'),
        ),
        migrations.AddConstraint(
            model_name='competicioaparell',
            constraint=models.UniqueConstraint(fields=('competicio', 'aparell'), name='uniq_competicio_aparell'),
        ),
    ]
