# Generated by Django 4.2 on 2026-01-16 11:19

from django.db import migrations, models
import django.db.models.deletion

def fill_comp_aparell(apps, schema_editor):
    TrampoliNota = apps.get_model("competicions_trampoli", "TrampoliNota")
    CompeticioAparell = apps.get_model("competicions_trampoli", "CompeticioAparell")

    # per cada nota amb NULL, assigna el primer aparell de la seva competició
    for nota in TrampoliNota.objects.filter(comp_aparell__isnull=True):
        ca = (CompeticioAparell.objects
              .filter(competicio_id=nota.competicio_id)
              .order_by("ordre", "id")
              .first())
        if ca:
            nota.comp_aparell_id = ca.id
            nota.save(update_fields=["comp_aparell"])

class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0012_aparell_competicioaparell_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_comp_aparell, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='trampolinota',
            name='comp_aparell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='competicions_trampoli.competicioaparell'),
        ),
    ]
