# Generated by Django 4.2 on 2026-01-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0013_alter_trampolinota_comp_aparell'),
    ]

    operations = [
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='criteri_execucio',
            field=models.CharField(choices=[('totes', 'Totes (mitjana)'), ('eliminar_extrems', 'Eliminar extrems'), ('maximes', 'Notes màximes'), ('minimes', 'Notes mínimes')], default='totes', max_length=20, verbose_name='Criteri selecció execució'),
        ),
        migrations.AddField(
            model_name='trampoliconfiguracio',
            name='nombre_notes_valides_execucio',
            field=models.PositiveSmallIntegerField(default=3, verbose_name="Nombre de notes d'execució vàlides"),
        ),
    ]
