# Generated by Django 4.2 on 2026-01-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0014_trampoliconfiguracio_criteri_execucio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trampolinota',
            name='execucio_manuals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
