# Generated by Django 4.2 on 2026-01-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0015_trampolinota_execucio_manuals'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotacioFranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inici', models.TimeField()),
                ('hora_fi', models.TimeField()),
                ('ordre', models.PositiveIntegerField(db_index=True, default=1)),
                ('titol', models.CharField(blank=True, default='', max_length=120)),
                ('competicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rot_franges', to='competicions_trampoli.competicio')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RotacioEstacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('aparell', 'Aparell'), ('descans', 'Descans')], default='aparell', max_length=10)),
                ('nom_override', models.CharField(blank=True, default='', max_length=120)),
                ('ordre', models.PositiveIntegerField(db_index=True, default=1)),
                ('actiu', models.BooleanField(default=True)),
                ('comp_aparell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rot_estacions', to='competicions_trampoli.competicioaparell')),
                ('competicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rot_estacions', to='competicions_trampoli.competicio')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RotacioAssignacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup', models.PositiveIntegerField(blank=True, null=True)),
                ('competicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rot_assignacions', to='competicions_trampoli.competicio')),
                ('estacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignacions', to='competicions_trampoli.rotacioestacio')),
                ('franja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignacions', to='competicions_trampoli.rotaciofranja')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rotaciofranja',
            constraint=models.UniqueConstraint(fields=('competicio', 'ordre'), name='uniq_rot_franja_ordre'),
        ),
        migrations.AddConstraint(
            model_name='rotacioestacio',
            constraint=models.UniqueConstraint(condition=models.Q(('comp_aparell__isnull', False)), fields=('competicio', 'comp_aparell'), name='uniq_rot_estacio_per_comp_aparell_notnull'),
        ),
        migrations.AddIndex(
            model_name='rotacioassignacio',
            index=models.Index(fields=['competicio', 'grup'], name='competicion_competi_8c61a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='rotacioassignacio',
            constraint=models.UniqueConstraint(fields=('franja', 'estacio'), name='uniq_rot_cell'),
        ),
    ]
