# Generated by Django 4.2 on 2026-01-19 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0016_rotaciofranja_rotacioestacio_rotacioassignacio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Nova classificació', max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('tipus', models.CharField(choices=[('individual', 'Individual'), ('entitat', 'Entitat')], default='individual', max_length=20)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacions_cfg', to='competicions_trampoli.competicio')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassificacioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particio_key', models.CharField(db_index=True, max_length=255)),
                ('resultat', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classificacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='competicions_trampoli.classificacioconfig')),
            ],
            options={
                'ordering': ['particio_key'],
                'unique_together': {('classificacio', 'particio_key')},
            },
        ),
    ]
