# Generated by Django 4.2 on 2026-01-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0017_classificacioconfig_classificaciocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_aparell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_schema', to='competicions_trampoli.competicioaparell')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercici', models.PositiveSmallIntegerField(default=1)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_aparell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competicions_trampoli.competicioaparell')),
                ('competicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competicions_trampoli.competicio')),
                ('inscripcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competicions_trampoli.inscripcio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scoreentry',
            constraint=models.UniqueConstraint(fields=('competicio', 'inscripcio', 'exercici', 'comp_aparell'), name='uniq_scoreentry_per_exercici_aparell'),
        ),
    ]
