# Generated by Django 4.2 on 2026-02-05 11:07

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    ScoringSchema = apps.get_model("competicions_trampoli", "ScoringSchema")

    # IMPORTANT:
    # ordenem per id perquè l'últim sigui el "més recent"
    schemas = ScoringSchema.objects.select_related(
        "comp_aparell__aparell"
    ).order_by("id")

    used_aparells = set()

    for schema in schemas:
        if not schema.comp_aparell_id:
            continue

        aparell_id = schema.comp_aparell.aparell_id

        if not aparell_id:
            continue

        # si aquest aparell ja té schema global, saltem
        if aparell_id in used_aparells:
            continue

        schema.aparell_id = aparell_id
        schema.save(update_fields=["aparell"])

        used_aparells.add(aparell_id)


def reverse(apps, schema_editor):
    ScoringSchema = apps.get_model("competicions_trampoli", "ScoringSchema")

    # rollback: traiem l'enllaç global
    for schema in ScoringSchema.objects.exclude(aparell=None):
        schema.aparell = None
        schema.save(update_fields=["aparell"])


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0018_scoringschema_scoreentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringschema',
            name='aparell',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scoring_schema',
                to='competicions_trampoli.aparell',
            ),
        ),

        migrations.RunPython(forward, reverse),
    ]
