# Generated by Django 4.2 on 2026-02-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0019_scoringschema_aparell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringschema',
            name='comp_aparell',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_schema', to='competicions_trampoli.competicioaparell'),
        ),
    ]
