# Generated by Django 4.2 on 2026-02-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0020_alter_scoringschema_comp_aparell'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicioaparell',
            name='nombre_exercicis',
            field=models.PositiveSmallIntegerField(default=1, max_length=10, verbose_name="Nombre d'exercicis"),
        ),
    ]
