# Generated by Django 4.2 on 2026-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0021_competicioaparell_nombre_exercicis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicioaparell',
            name='nombre_exercicis',
            field=models.PositiveSmallIntegerField(default=1, max_length=2, verbose_name="Nombre d'exercicis"),
        ),
    ]
