# Generated by Django 4.2 on 2026-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0023_alter_competicioaparell_nombre_exercicis'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicio',
            name='inscripcions_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inscripcio',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
