# Generated by Django 4.2 on 2026-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0025_judgedevicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicio',
            name='inscripcions_view',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
