# Generated by Django 4.2 on 2026-02-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0026_competicio_inscripcions_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=20)),
                ('criteri', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='competicions_trampoli.competicio')),
            ],
            options={
                'ordering': ['nom', 'id'],
            },
        ),
        migrations.AddField(
            model_name='inscripcio',
            name='equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='competicions_trampoli.equip'),
        ),
        migrations.AddIndex(
            model_name='equip',
            index=models.Index(fields=['competicio', 'nom'], name='competicion_competi_09e48b_idx'),
        ),
        migrations.AddConstraint(
            model_name='equip',
            constraint=models.UniqueConstraint(fields=('competicio', 'nom'), name='uniq_equip_nom_per_competicio'),
        ),
    ]
