# Generated by Django 4.2 on 2026-02-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0027_equip_inscripcio_equip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcio',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='inscripcio',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False), models.Q(('dedupe_key', ''), _negated=True)), fields=('competicio', 'dedupe_key'), name='uniq_inscripcio_competicio_dedupe_key'),
        ),
    ]
