# Generated by Django 4.2 on 2026-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0028_inscripcio_dedupe_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotacioassignacio',
            name='grups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='classificacioconfig',
            name='tipus',
            field=models.CharField(choices=[('individual', 'Individual'), ('entitat', 'Entitat'), ('equips', 'Equips')], default='individual', max_length=20),
        ),
    ]
