# Generated by Django 4.2 on 2026-02-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0029_rotacioassignacio_grups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcioAparellExclusio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiu', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_aparell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcions_excloses', to='competicions_trampoli.competicioaparell')),
                ('inscripcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aparells_exclosos', to='competicions_trampoli.inscripcio')),
            ],
        ),
        migrations.AddIndex(
            model_name='inscripcioaparellexclusio',
            index=models.Index(fields=['comp_aparell', 'inscripcio'], name='competicion_comp_ap_7c14e4_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcioaparellexclusio',
            index=models.Index(fields=['inscripcio', 'comp_aparell'], name='competicion_inscrip_70c150_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscripcioaparellexclusio',
            constraint=models.UniqueConstraint(fields=('inscripcio', 'comp_aparell'), name='uniq_inscripcio_comp_aparell_exclusio'),
        ),
    ]
