# Generated by Django 4.2 on 2026-02-25 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("competicions_trampoli", "0030_inscripcioaparellexclusio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicLiveToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "competicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_live_tokens",
                        to="competicions_trampoli.competicio",
                    ),
                ),
            ],
        ),
    ]
