# Generated by Django 4.2 on 2026-02-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0033_scoreentryvideoevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scoreentryvideo',
            new_name='competicion_status_1bf60d_idx',
            old_name='competicion_status_26cc34_idx',
        ),
        migrations.RenameIndex(
            model_name='scoreentryvideo',
            new_name='competicion_judge_t_76fa42_idx',
            old_name='competicion_judge_t_89f5da_idx',
        ),
        migrations.RenameIndex(
            model_name='scoreentryvideoevent',
            new_name='competicion_competi_8e4a34_idx',
            old_name='comp_videoev_comp_e7ce10_idx',
        ),
        migrations.RenameIndex(
            model_name='scoreentryvideoevent',
            new_name='competicion_action_0471db_idx',
            old_name='comp_videoev_action_1e0f95_idx',
        ),
        migrations.RenameIndex(
            model_name='scoreentryvideoevent',
            new_name='competicion_judge_t_67b99d_idx',
            old_name='comp_videoev_judge_8c85e0_idx',
        ),
        migrations.RenameIndex(
            model_name='scoreentryvideoevent',
            new_name='competicion_score_e_3eec5d_idx',
            old_name='comp_videoev_score_0f43f8_idx',
        ),
    ]
