# Generated by Django 4.2 on 2026-03-06 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("competicions_trampoli", "0037_judgedevicetoken_can_record_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificacioTemplateGlobal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("descripcio", models.CharField(blank=True, default="", max_length=255)),
                ("activa", models.BooleanField(default=True)),
                (
                    "tipus",
                    models.CharField(
                        choices=[("individual", "Individual"), ("entitat", "Entitat"), ("equips", "Equips")],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("requirements", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classificacio_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nom", "id"],
            },
        ),
    ]
