# Generated by Codex on 2026-03-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("competicions_trampoli", "0038_classificaciotemplateglobal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aparell",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aparells_creats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="aparell",
            name="codi",
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name="aparell",
            index=models.Index(fields=["created_by", "nom"], name="competicion_created_c5f6cf_idx"),
        ),
        migrations.AddIndex(
            model_name="aparell",
            index=models.Index(fields=["created_by", "actiu"], name="competicion_created_0e666d_idx"),
        ),
    ]
