# Generated by Codex on 2026-03-06

import copy

from django.conf import settings
from django.db import migrations, models
from django.db.models import Case, IntegerField, Value, When
import django.db.models.deletion


def _get_auth_user_model(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".", 1)
    return apps.get_model(app_label, model_name)


def _resolve_fallback_user_id(apps, db_alias):
    User = _get_auth_user_model(apps)
    fallback_user_id = (
        User.objects.using(db_alias)
        .filter(is_superuser=True)
        .order_by("id")
        .values_list("id", flat=True)
        .first()
    )
    if fallback_user_id:
        return fallback_user_id

    fallback_user_id = (
        User.objects.using(db_alias)
        .order_by("id")
        .values_list("id", flat=True)
        .first()
    )
    if fallback_user_id:
        return fallback_user_id

    raise RuntimeError("No hi ha usuaris al sistema per assignar created_by als aparells.")


def _build_owner_map(apps, db_alias):
    CompeticioMembership = apps.get_model("competicions_trampoli", "CompeticioMembership")
    owner_rank = Case(
        When(role="owner", then=Value(0)),
        When(role="editor", then=Value(1)),
        default=Value(99),
        output_field=IntegerField(),
    )
    rows = (
        CompeticioMembership.objects.using(db_alias)
        .filter(is_active=True)
        .annotate(owner_rank=owner_rank)
        .order_by("competicio_id", "owner_rank", "id")
        .values_list("competicio_id", "user_id", "owner_rank")
    )
    owner_by_comp = {}
    for competicio_id, user_id, rank in rows:
        if rank > 1:
            continue
        owner_by_comp.setdefault(competicio_id, user_id)
    return owner_by_comp


def _owner_for_comp(competicio_id, owner_by_comp, fallback_user_id):
    return owner_by_comp.get(competicio_id) or fallback_user_id


def backfill_aparell_created_by(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Aparell = apps.get_model("competicions_trampoli", "Aparell")
    CompeticioAparell = apps.get_model("competicions_trampoli", "CompeticioAparell")
    ScoringSchema = apps.get_model("competicions_trampoli", "ScoringSchema")

    # Test databases can be empty when migrations run for the first time.
    # In that case there is nothing to backfill and no fallback user is needed.
    if not Aparell.objects.using(db_alias).exists():
        return

    fallback_user_id = _resolve_fallback_user_id(apps, db_alias)
    owner_by_comp = _build_owner_map(apps, db_alias)

    for ap in Aparell.objects.using(db_alias).order_by("id"):
        links = list(
            CompeticioAparell.objects.using(db_alias)
            .filter(aparell_id=ap.id)
            .values("id", "competicio_id")
        )

        if not links:
            target_owner_id = ap.created_by_id or fallback_user_id
            if ap.created_by_id != target_owner_id:
                ap.created_by_id = target_owner_id
                ap.save(update_fields=["created_by"])
            continue

        owner_ids = {
            _owner_for_comp(link["competicio_id"], owner_by_comp, fallback_user_id)
            for link in links
        }
        if not owner_ids:
            owner_ids = {fallback_user_id}

        if len(owner_ids) == 1:
            target_owner_id = next(iter(owner_ids))
            if ap.created_by_id != target_owner_id:
                ap.created_by_id = target_owner_id
                ap.save(update_fields=["created_by"])
            continue

        canonical_owner_id = ap.created_by_id if ap.created_by_id in owner_ids else min(owner_ids)
        if ap.created_by_id != canonical_owner_id:
            ap.created_by_id = canonical_owner_id
            ap.save(update_fields=["created_by"])

        base_schema = (
            ScoringSchema.objects.using(db_alias)
            .filter(aparell_id=ap.id)
            .only("id", "schema")
            .first()
        )

        for owner_id in sorted(owner_ids):
            if owner_id == canonical_owner_id:
                continue

            clone = (
                Aparell.objects.using(db_alias)
                .filter(created_by_id=owner_id, codi=ap.codi)
                .order_by("id")
                .first()
            )
            if clone is None:
                clone = Aparell.objects.using(db_alias).create(
                    codi=ap.codi,
                    nom=ap.nom,
                    actiu=ap.actiu,
                    created_by_id=owner_id,
                )

            if base_schema and not (
                ScoringSchema.objects.using(db_alias)
                .filter(aparell_id=clone.id)
                .exists()
            ):
                ScoringSchema.objects.using(db_alias).create(
                    comp_aparell_id=None,
                    aparell_id=clone.id,
                    schema=copy.deepcopy(base_schema.schema or {}),
                )

            target_comp_ids = {
                link["competicio_id"]
                for link in links
                if _owner_for_comp(link["competicio_id"], owner_by_comp, fallback_user_id) == owner_id
            }
            for link in links:
                if link["competicio_id"] not in target_comp_ids:
                    continue
                ca = CompeticioAparell.objects.using(db_alias).get(pk=link["id"])
                if ca.aparell_id == clone.id:
                    continue
                conflict = (
                    CompeticioAparell.objects.using(db_alias)
                    .filter(competicio_id=ca.competicio_id, aparell_id=clone.id)
                    .exclude(pk=ca.id)
                    .exists()
                )
                if conflict:
                    continue
                ca.aparell_id = clone.id
                ca.save(update_fields=["aparell"])


class Migration(migrations.Migration):
    dependencies = [
        ("competicions_trampoli", "0039_aparell_created_by_phase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_aparell_created_by, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="aparell",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aparells_creats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="aparell",
            constraint=models.UniqueConstraint(
                fields=("created_by", "codi"),
                name="uniq_aparell_created_by_codi",
            ),
        ),
    ]
