# Generated by Codex on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competicions_trampoli", "0040_aparell_created_by_phase2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificaciotemplateglobal",
            name="slug",
            field=models.SlugField(max_length=180),
        ),
        migrations.AddIndex(
            model_name="classificaciotemplateglobal",
            index=models.Index(fields=["created_by", "nom"], name="classif_tpl_owner_nom_idx"),
        ),
        migrations.AddIndex(
            model_name="classificaciotemplateglobal",
            index=models.Index(fields=["created_by", "activa"], name="classif_tpl_owner_actiu_idx"),
        ),
    ]
