# Generated by Codex on 2026-03-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("competicions_trampoli", "0042_classificacio_template_owner_phase2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeConversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("requested", "Requested"),
                            ("ack", "Ack"),
                            ("resolved", "Resolved"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("high", "High")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("unread_for_org", models.PositiveIntegerField(default=0)),
                ("unread_for_judge", models.PositiveIntegerField(default=0)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("org_last_read_at", models.DateTimeField(blank=True, null=True)),
                ("judge_last_read_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_preview", models.CharField(blank=True, default="", max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comp_aparell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_conversations",
                        to="competicions_trampoli.competicioaparell",
                    ),
                ),
                (
                    "competicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_conversations",
                        to="competicions_trampoli.competicio",
                    ),
                ),
                (
                    "judge_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="competicions_trampoli.judgedevicetoken",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competicio", "status", "last_message_at"],
                        name="judgeconv_comp_status_last_idx",
                    ),
                    models.Index(
                        fields=["competicio", "unread_for_org", "last_message_at"],
                        name="judgeconv_comp_unread_last_idx",
                    ),
                    models.Index(fields=["judge_token", "updated_at"], name="judgeconv_token_updated_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JudgeConversationMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("judge", "Judge"), ("organization", "Organization"), ("system", "System")],
                        max_length=20,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("support_request", "Support Request"),
                            ("support_request_quick", "Support Request Quick"),
                            ("reply", "Reply"),
                            ("instruction", "Instruction"),
                            ("system", "System"),
                        ],
                        default="reply",
                        max_length=30,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comp_aparell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_conversation_messages",
                        to="competicions_trampoli.competicioaparell",
                    ),
                ),
                (
                    "competicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_conversation_messages",
                        to="competicions_trampoli.competicio",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="competicions_trampoli.judgeconversation",
                    ),
                ),
                (
                    "judge_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_messages",
                        to="competicions_trampoli.judgedevicetoken",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="judge_conversation_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["conversation", "created_at"], name="judgeconvmsg_conv_created_idx"),
                    models.Index(fields=["competicio", "created_at"], name="judgeconvmsg_comp_created_idx"),
                    models.Index(fields=["judge_token", "created_at"], name="judgeconvmsg_token_created_idx"),
                    models.Index(fields=["message_type", "created_at"], name="judgeconvmsg_type_created_idx"),
                ],
            },
        ),
    ]
