# Generated by Codex on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("competicions_trampoli", "0046_grupcompeticio_and_competition_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=80)),
                ("nom", models.CharField(max_length=180)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("competicio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equip_contexts", to="competicions_trampoli.competicio")),
            ],
            options={
                "ordering": ["nom", "id"],
            },
        ),
        migrations.CreateModel(
            name="InscripcioEquipAssignacio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origen", models.CharField(choices=[("manual", "Manual"), ("auto", "Automatic")], default="manual", max_length=20)),
                ("criteri", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("competicio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equip_assignacions", to="competicions_trampoli.competicio")),
                ("context", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignacions", to="competicions_trampoli.equipcontext")),
                ("equip", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignacions_contextuals", to="competicions_trampoli.equip")),
                ("inscripcio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equip_assignacions", to="competicions_trampoli.inscripcio")),
            ],
            options={
                "ordering": ["context_id", "inscripcio_id"],
            },
        ),
        migrations.AddIndex(
            model_name="equipcontext",
            index=models.Index(fields=["competicio", "code"], name="competicion_competi_5ff36a_idx"),
        ),
        migrations.AddIndex(
            model_name="inscripcioequipassignacio",
            index=models.Index(fields=["competicio", "context"], name="competicion_competi_6181ab_idx"),
        ),
        migrations.AddIndex(
            model_name="inscripcioequipassignacio",
            index=models.Index(fields=["competicio", "inscripcio"], name="competicion_competi_70071c_idx"),
        ),
        migrations.AddConstraint(
            model_name="equipcontext",
            constraint=models.UniqueConstraint(fields=("competicio", "code"), name="uniq_equip_context_code_per_competicio"),
        ),
        migrations.AddConstraint(
            model_name="inscripcioequipassignacio",
            constraint=models.UniqueConstraint(fields=("context", "inscripcio"), name="uniq_equip_assignacio_context_inscripcio"),
        ),
    ]
