# Generated by Django 4.2 on 2026-03-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0049_global_team_aparells'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='competicioaparellequipcontextsource',
            new_name='competicion_competi_63994e_idx',
            old_name='competicion_competi_41f8ab_idx',
        ),
        migrations.RenameIndex(
            model_name='competicioaparellequipcontextsource',
            new_name='competicion_competi_39825f_idx',
            old_name='competicion_competi_0f6f6c_idx',
        ),
        migrations.RenameIndex(
            model_name='equipcontext',
            new_name='competicion_competi_c0b2af_idx',
            old_name='competicion_competi_5ff36a_idx',
        ),
        migrations.RenameIndex(
            model_name='grupcompeticio',
            new_name='competicion_competi_201eb7_idx',
            old_name='competicion_competi_ef4a46_idx',
        ),
        migrations.RenameIndex(
            model_name='inscripcio',
            new_name='competicion_competi_ec7007_idx',
            old_name='competicion_competi_1c7a67_idx',
        ),
        migrations.RenameIndex(
            model_name='inscripcioequipassignacio',
            new_name='competicion_competi_b74348_idx',
            old_name='competicion_competi_6181ab_idx',
        ),
        migrations.RenameIndex(
            model_name='inscripcioequipassignacio',
            new_name='competicion_competi_d05a55_idx',
            old_name='competicion_competi_70071c_idx',
        ),
        migrations.RenameIndex(
            model_name='rotacioassignaciogrup',
            new_name='competicion_grup_id_14a83a_idx',
            old_name='competicion_grup_id_9570d4_idx',
        ),
        migrations.RenameIndex(
            model_name='teamcompetitivesubject',
            new_name='competicion_competi_6bcf36_idx',
            old_name='competicion_competi_4e5f33_idx',
        ),
        migrations.RenameIndex(
            model_name='teamcompetitivesubject',
            new_name='competicion_competi_f78bd7_idx',
            old_name='competicion_competi_c56fca_idx',
        ),
        migrations.RenameIndex(
            model_name='teamscoreentry',
            new_name='competicion_competi_bc6784_idx',
            old_name='competicion_competi_1db8d6_idx',
        ),
        migrations.RenameIndex(
            model_name='teamscoreentry',
            new_name='competicion_competi_6cc77a_idx',
            old_name='competicion_competi_6f7f66_idx',
        ),
        migrations.RenameIndex(
            model_name='teamscoreentryvideo',
            new_name='competicion_status_b5b581_idx',
            old_name='competicion_status_25d19e_idx',
        ),
        migrations.RenameIndex(
            model_name='teamscoreentryvideo',
            new_name='competicion_judge_t_ec8b4b_idx',
            old_name='competicion_judge_t_521b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='teamscoreentryvideoevent',
            new_name='competicion_competi_891a00_idx',
            old_name='competicion_competi_2d4a94_idx',
        ),
        migrations.RenameIndex(
            model_name='teamscoreentryvideoevent',
            new_name='competicion_action_a21d8c_idx',
            old_name='competicion_action__1af2ee_idx',
        ),
        migrations.RenameIndex(
            model_name='teamscoreentryvideoevent',
            new_name='competicion_judge_t_6a96a2_idx',
            old_name='competicion_judge_t_2a4c56_idx',
        ),
        migrations.RenameIndex(
            model_name='teamscoreentryvideoevent',
            new_name='competicion_team_sc_df6c4c_idx',
            old_name='competicion_team_sc_ba7619_idx',
        ),
        migrations.AlterField(
            model_name='competicioaparell',
            name='mode_execucio',
            field=models.CharField(choices=[('salts', 'Per elements'), ('manual', 'Execucio global manual')], default='salts', max_length=10),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='criteri_execucio',
            field=models.CharField(choices=[('totes', 'Totes (mitjana)'), ('eliminar_extrems', 'Eliminar extrems'), ('maximes', 'Notes maximes'), ('minimes', 'Notes minimes')], default='totes', max_length=20, verbose_name='Criteri seleccio execucio'),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='mode_execucio',
            field=models.CharField(choices=[('salts', 'Per salts (S1..S11)'), ('manual', 'Execucio global manual')], default='salts', max_length=10),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='mostrar_penalitzacio',
            field=models.BooleanField(default=True, verbose_name='Mostrar Penalitzacio'),
        ),
        migrations.AlterField(
            model_name='trampoliconfiguracio',
            name='nombre_notes_valides_execucio',
            field=models.PositiveSmallIntegerField(default=3, verbose_name="Nombre de notes d'execucio valides"),
        ),
    ]
