# Generated by Django 4.2 on 2026-04-09 16:11

from django.db import migrations, models


def backfill_ordre_visual(apps, schema_editor):
    RotacioFranja = apps.get_model("competicions_trampoli", "RotacioFranja")
    for franja in RotacioFranja.objects.all().only("id", "ordre"):
        RotacioFranja.objects.filter(pk=franja.pk).update(ordre_visual=franja.ordre)


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0055_rotaciofranja_tipus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaciofranja',
            name='color_fons',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='rotaciofranja',
            name='ordre_visual',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.RunPython(backfill_ordre_visual, migrations.RunPython.noop),
    ]
