# Generated by Django 4.2 on 2026-05-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0064_classificacioconfig_publicada'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('previewed', 'Previsualitzada'), ('applied', 'Aplicada'), ('stale', 'Obsoleta')], default='previewed', max_length=30)),
                ('snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_runs', to='competicions_trampoli.competicioaparellfase')),
                ('source_classificacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_runs', to='competicions_trampoli.classificacioconfig')),
                ('source_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_source_runs', to='competicions_trampoli.competicioaparellfase')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FasePartitionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('generated', 'Generada'), ('confirmed', 'Confirmada'), ('stale', 'Obsoleta')], default='generated', max_length=30)),
                ('source_snapshot_hash', models.CharField(blank=True, default='', max_length=64)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partition_states', to='competicions_trampoli.competicioaparellfase')),
                ('qualification_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partition_states', to='competicions_trampoli.qualificationrun')),
            ],
            options={
                'ordering': ['fase_id', 'partition_key'],
            },
        ),
        migrations.AddIndex(
            model_name='qualificationrun',
            index=models.Index(fields=['fase', 'status'], name='qualification_fase_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qualificationrun',
            index=models.Index(fields=['source_classificacio', 'status'], name='qualification_src_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fasepartitionstate',
            index=models.Index(fields=['fase', 'status'], name='fasepart_fase_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='fasepartitionstate',
            constraint=models.UniqueConstraint(fields=('fase', 'partition_key'), name='uniq_fase_partition_state'),
        ),
    ]
