# Generated by Django 4.2 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competicions_trampoli", "0065_qualification_runs"),
    ]

    operations = [
        migrations.AddField(
            model_name="competicioaparell",
            name="participation_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
