# Generated by Django 4.2 on 2026-05-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0069_backfill_local_scoring_schemas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicio',
            name='tipus',
            field=models.CharField(choices=[('natacio', 'Natació'), ('patinatge', 'Patinatge'), ('trampoli', 'Gimnàstica trampolí'), ('artistica', 'Gimnàstica artística'), ('ritmica', 'Gimnastica ritmica')], default='trampoli', max_length=20),
        ),
    ]
