# Generated by Codex on 2026-06-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("competicions_trampoli", "0070_alter_competicio_tipus"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscripcioBaixa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("motiu", models.CharField(blank=True, default="", max_length=250)),
                ("notes", models.TextField(blank=True, default="")),
                ("anul_lada_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anul_lada_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscripcions_baixes_anullades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comp_aparell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baixes",
                        to="competicions_trampoli.competicioaparell",
                    ),
                ),
                (
                    "competicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripcions_baixes",
                        to="competicions_trampoli.competicio",
                    ),
                ),
                (
                    "inscripcio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baixes",
                        to="competicions_trampoli.inscripcio",
                    ),
                ),
                (
                    "marcada_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscripcions_baixes_marcades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="inscripciobaixa",
            index=models.Index(fields=["competicio", "inscripcio"], name="baixacomp_inscripcio_idx"),
        ),
        migrations.AddIndex(
            model_name="inscripciobaixa",
            index=models.Index(fields=["competicio", "comp_aparell"], name="baixacomp_aparell_idx"),
        ),
        migrations.AddIndex(
            model_name="inscripciobaixa",
            index=models.Index(fields=["competicio", "anul_lada_at"], name="baixacomp_activa_idx"),
        ),
        migrations.AddConstraint(
            model_name="inscripciobaixa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comp_aparell__isnull", True), ("anul_lada_at__isnull", True)),
                fields=("competicio", "inscripcio"),
                name="uniq_baixa_global_activa_inscripcio",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscripciobaixa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comp_aparell__isnull", False), ("anul_lada_at__isnull", True)),
                fields=("competicio", "inscripcio", "comp_aparell"),
                name="uniq_baixa_aparell_activa_inscripcio",
            ),
        ),
    ]
