# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competicions_trampoli", "0071_inscripciobaixa"),
    ]

    operations = [
        migrations.AddField(
            model_name="competicio",
            name="data_fi",
            field=models.DateField(blank=True, null=True),
        ),
    ]
