from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="iatrain_home"),
    path("perfils/actualitzar/", views.update_profile, name="iatrain_profile_update"),
    path("perspectiva/", views.select_perspective, name="iatrain_perspective"),
    path("biblioteca/", views.library, name="iatrain_library"),
    path("gimnastes/", views.athlete_list, name="iatrain_athlete_list"),
    path("gimnastes/afegir/", views.athlete_create, name="iatrain_athlete_create"),
    path("gimnastes/<int:pk>/", views.athlete_detail, name="iatrain_athlete_detail"),
    path("revisions/", views.profile_review, name="iatrain_profile_review"),
    path("revisions/condicions/<int:pk>/", views.condition_review, name="iatrain_condition_review"),
    path("revisions/condicions/<int:pk>/resoldre/", views.condition_resolve, name="iatrain_condition_resolve"),
    path("revisions/interpretacions/<int:pk>/", views.insight_review, name="iatrain_insight_review"),
    path("grups/", views.group_list, name="iatrain_group_list"),
    path("grups/crear/", views.group_create, name="iatrain_group_create"),
    path("grups/<int:pk>/", views.group_detail, name="iatrain_group_detail"),
    path("grups/<int:pk>/membres/<int:membership_pk>/retirar/", views.group_member_remove, name="iatrain_group_member_remove"),
    path("organitzacions/", views.organization_list, name="iatrain_organization_list"),
    path("organitzacions/<slug:slug>/", views.organization_detail, name="iatrain_organization_detail"),
    path("gimnasos/", views.gym_list, name="iatrain_gym_list"),
    path("gimnasos/crear/", views.gym_create, name="iatrain_gym_create"),
    path("gimnasos/<int:pk>/", views.gym_detail, name="iatrain_gym_detail"),
    path("gimnasos/<int:pk>/editar/", views.gym_edit, name="iatrain_gym_edit"),
    path("gimnasos/<int:pk>/material/afegir/", views.gym_equipment_create, name="iatrain_gym_equipment_create"),
    path("gimnasos/<int:pk>/material/<int:equipment_pk>/editar/", views.gym_equipment_edit, name="iatrain_gym_equipment_edit"),
    path("engine/comencar/", views.training_start, name="iatrain_training_start"),
    path("engine/context-options/", views.context_options, name="iatrain_engine_context_options"),
    path("sessions/", views.session_list, name="iatrain_session_list"),
    path("sessions/<int:pk>/", views.session_detail, name="iatrain_session_detail"),
    path("sessions/<int:pk>/generacions/bloc/", views.block_generation_create, name="iatrain_block_generation_create"),
    path("sessions/<int:pk>/generacions/<int:run_pk>/reformular/", views.block_generation_refine, name="iatrain_block_generation_refine"),
    path("sessions/<int:pk>/generacions/<int:run_pk>/estat/", views.block_generation_status, name="iatrain_block_generation_status"),
    path("sessions/<int:pk>/generacions/<int:run_pk>/decidir/", views.block_generation_decide, name="iatrain_block_generation_decide"),
    path("sessions/<int:pk>/generacions/<int:run_pk>/aplicar/", views.block_generation_apply, name="iatrain_block_generation_apply"),
    path("sessions/<int:pk>/generacions/<int:run_pk>/descartar/", views.block_generation_discard, name="iatrain_block_generation_discard"),
    path("sessions/<int:pk>/participants/<int:participant_pk>/eliminar/", views.session_participant_delete, name="iatrain_session_participant_delete"),
    path("sessions/<int:pk>/objectius/<int:goal_pk>/eliminar/", views.session_goal_delete, name="iatrain_session_goal_delete"),
    path("sessions/<int:pk>/blocs/<int:block_pk>/eliminar/", views.session_block_delete, name="iatrain_session_block_delete"),
    path("sessions/<int:pk>/blocs/<int:block_pk>/editar/", views.session_block_edit, name="iatrain_session_block_edit"),
    path("sessions/<int:pk>/blocs/<int:block_pk>/items/afegir/", views.session_item_create, name="iatrain_session_item_create"),
    path("sessions/<int:pk>/items/<int:item_pk>/editar/", views.session_item_edit, name="iatrain_session_item_edit"),
    path("sessions/<int:pk>/items/<int:item_pk>/eliminar/", views.session_item_delete, name="iatrain_session_item_delete"),
    path("sessions/<int:pk>/versions/<int:revision_pk>/estat/", views.session_revision_transition, name="iatrain_session_revision_transition"),
    path("graf-coneixement/", views.knowledge_graph, name="iatrain_knowledge_graph"),
    path("graf-coneixement/dades/", views.knowledge_graph_data, name="iatrain_knowledge_graph_data"),
    path(
        "graf-coneixement/conceptes/<int:pk>/estat/",
        views.knowledge_concept_status,
        name="iatrain_knowledge_concept_status",
    ),
    path(
        "graf-coneixement/relacions/<int:pk>/estat/",
        views.knowledge_relation_status,
        name="iatrain_knowledge_relation_status",
    ),
    path(
        "graf-coneixement/anatomia/conceptes/<int:pk>/estat/",
        views.motion_concept_status,
        name="iatrain_motion_concept_status",
    ),
    path(
        "graf-coneixement/anatomia/relacions/<int:pk>/estat/",
        views.motion_relation_status,
        name="iatrain_motion_relation_status",
    ),
]
